#!/usr/bin/env python3
"""Bake .bsnp training snapshots for the batched env (blaze).

For every seed in rl/out/coal_prefixes.json: replay the scripted prefix
(chain_probe.make_env), then for each curriculum stage d in STAGES run
chain_probe.stage_coal(stop_dist=d) to burrow within d blocks of the nearest
coal, quiesce QUIESCE no-op ticks (drops settle / get picked up, dig delay
drains), and dump rl/out/snaps/s<seed>_d<d>.bsnp via the env's "snapshot"
action key with a CURRICULUM_R-block region radius (default T0_R=64, so
2R x 128 x 2R). Snapshots whose region contains liquid (ids 8-11) are
FLAGGED - blaze does not simulate the fluids CA, so flagged (seed,stage)
pairs must not be used for batched training.

--t0 mode bakes FRESH-SPAWN tick-0 snapshots instead (s<seed>_t0.bsnp, one
per coal_prefixes.json seed) with a --t0-r block region radius (default 64:
the s10 full chain wanders <= 5 blocks from spawn and camera rays reach 49,
so 64 covers every ray of the whole spawn-to-torch episode). Tick-0 needs no
quiesce: the state IS the clean post-init pre-first-tick boundary (verified
byte-exact by verify_cpu.py --chain).

--chain-stages bakes frontier curriculum start states (s<seed>_stg{1..4}.bsnp)
from a full spawn-to-torch action sequence. Seed 10 replays the committed
rl/out/chain_actions_s10.json; every other seed is generated by
chain_probe.run_seed (chop/craft/dig/mine_coal). A run_seed failure skips
that seed (probe-failed). For each reached stage the FIRST tick where
cr_stage_of_best's predicate becomes true is captured, then QUIESCE no-ops,
then dumped at CURRICULUM_R. Dump tick is written into the .bsnp header and
a sidecar .meta.json (first_action_idx, dump_tick, remainder_start).

A verify-emit pass then applies the t0 standard per stage snap: magma
--snapshot-in vs blaze CPU (fluids in PARITY_SUPPORTED) via verify_cpu.py
run_seed_parity, plus a liquid-quiescence fingerprint (ids 8-11 must not
change position or id). Census liquid is not an emit blocker; settled water
that never moves is the same class as the blessed t0 snaps. Remainder of
the seed's chain after the capture index is replayed, padded with no-ops
to at least 600 ticks. Emit requires digest equality on every tick, liquid
quiescence, and the existing blaze-CPU inventory predicate.

--verify-emit runs that pass on existing dumps without re-baking.

  stage 1: logs >= 3 OR planks >= 1
  stage 2: wood pickaxe >= 1
  stage 3: wood pickaxe >= 1 AND cobblestone >= 3
  stage 4: coal >= 1

Run (anvil):
  cd magma && uv run --no-project --with numpy \
      python blaze/env/make_snapshots.py
  cd magma && uv run --no-project --with numpy \
      python blaze/env/make_snapshots.py --t0
  cd magma && uv run --no-project --with numpy \
      python blaze/env/make_snapshots.py --chain-stages
  cd magma && uv run --no-project --with numpy \
      python blaze/env/make_snapshots.py --verify-emit
  cd magma && uv run --no-project --with numpy \
      python blaze/env/make_snapshots.py --expand   # re-dump old d* fixtures
                                                    # IN PLACE at CURRICULUM_R
"""
import argparse
from concurrent.futures import ThreadPoolExecutor, as_completed
import json
import math
import os
import struct
import subprocess
import sys

import numpy as np

RL = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "rl")  # blaze/rl
sys.path.insert(0, RL)

OUT = os.path.join(RL, "out")
SNAPS = os.path.join(OUT, "snaps")
STAGES = (6.0, 4.5, 3.0)
QUIESCE = 6
BUDGET = 3000
T0_R = 64
# Curriculum stage dumps used the rl_mode default radius (32 -> 64x128x64)
# until 2026-08-07. blaze's world IS the .bsnp region, so a camera ray
# (obs_camera.h OC_FAR=48) leaves any radius-32 fixture the moment the agent
# has a clear sightline: magma's sliding camreg hits real blocks where blaze
# must return air, and verify_cpu could never gate cam on these fixtures
# (measured: 46/46 differing cam pixels at s14_d6.0 tick 0 were rays that had
# left the region). Physics near the edge diverges the same way. Match T0_R
# so every fixture shares one region size (blaze_load_snapshots requires
# identical dims across loaded snapshots) and the camera stays inside.
CURRICULUM_R = 64
MAGMA = os.path.join(os.path.dirname(os.path.dirname(RL)), "magma")
GAME_BIN = os.path.join(MAGMA, "magma_game")
ENV_DIR = os.path.dirname(os.path.abspath(__file__))
CPU_SO = os.path.join(ENV_DIR, "blaze_cpu.so")
# cr_stage_of_best predicates (chain_curr.c), independent first-true ticks.
CHAIN_STAGE_KS = (1, 2, 3, 4)
MIN_EMIT_TICKS = 600
STAGE_INDEX = os.path.join(OUT, "chain_stage_index.json")

# BOLR record size (packed, see game/rl_mode.c RlBinObs) - t0 mode reads raw
# records from magma_game --rl-bin without importing verify_cpu.
BIN_SIZE = sum(sz for sz in (4, 8, 8, 8, 8, 4, 4, 4, 36, 36, 4, 4, 36,
                             256 * 16, 64 * 12, 32 * 12,
                             2304 * 2, 2304, 2304))

# .bsnp header layout (blaze/env/blaze_snapshot.h): packed, little-endian.
HEAD_SIZE = 752
N_ITEMS_OFF = 724          # u32
RDIMS_OFF = 728            # 6 x i32: rx0,ry0,rz0,rnx,rny,rnz
ITEM_SIZE = 76


def quiesce(env, n=QUIESCE):
    for _ in range(n):
        cp.step(env, {"cam": 0})


def snap_liquid_flag(path):
    """(has_liquid, ncoal, rnx*rny*rnz) parsed straight from the file."""
    with open(path, "rb") as f:
        buf = f.read()
    assert buf[:4] == b"BSNP", path
    n_items = struct.unpack_from("<I", buf, N_ITEMS_OFF)[0]
    rnx, rny, rnz = struct.unpack_from("<6i", buf, RDIMS_OFF)[3:6]
    vol = rnx * rny * rnz
    off = HEAD_SIZE + ITEM_SIZE * n_items
    cells = np.frombuffer(buf, "<u2", vol, off)
    ids = cells >> 4
    has_liquid = bool(np.any((ids >= 8) & (ids <= 11)))
    ncoal = int(np.count_nonzero(ids == 16))
    return has_liquid, ncoal, vol

def strip_snapshot_liquid(path):
    """Replace liquid cells with air for a scoped non-fluid parity fixture."""
    with open(path, "rb") as f:
        buf = bytearray(f.read())
    n_items = struct.unpack_from("<I", buf, N_ITEMS_OFF)[0]
    rnx, rny, rnz = struct.unpack_from("<6i", buf, RDIMS_OFF)[3:6]
    vol = rnx * rny * rnz
    off = HEAD_SIZE + ITEM_SIZE * n_items
    cells = np.frombuffer(buf, "<u2", vol, off)
    ids = cells >> 4
    mask = (ids >= 8) & (ids <= 11)
    count = int(np.count_nonzero(mask))
    cells[mask] = 0
    with open(path, "wb") as f:
        f.write(buf)
    return count


def _exact(proc, n):
    buf = b""
    while len(buf) < n:
        c = proc.stdout.read(n - len(buf))
        if not c:
            raise RuntimeError("real env died")
        buf += c
    return buf

def relight_snapshot(path, seed, radius):
    """Round-trip an edited snapshot through Magma so its v2 light tail
    matches the edited block cells."""
    tmp = f"{path}.relight"
    p = subprocess.Popen(
        [GAME_BIN, "--rl-bin", "--render", "off", "--pace", "unlimited",
         "--seed", str(seed), "--mobs", "off", "--snapshot-in", path],
        stdin=subprocess.PIPE, stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL)
    try:
        _exact(p, BIN_SIZE)
        act = {"snapshot": tmp, "snapshot_r": radius, "cam": 0}
        p.stdin.write((json.dumps(act) + "\n").encode())
        p.stdin.flush()
        _exact(p, BIN_SIZE)
    finally:
        p.kill()
        p.wait()
    os.replace(tmp, path)


def bake_t0(seed, radius=None, path=None, strip_liquid=False):
    """Fresh-spawn tick-0 snapshot: spawn the real env (no --snapshot-in),
    consume the initial tick-0 BOLR record, then send a single action whose
    "snapshot" key is processed PRE-tick by rl_mode - so the dump is the
    exact tick-0 state, zero settle ticks needed."""
    if radius is None:
        radius = T0_R
    path = path or os.path.join(SNAPS, f"s{seed}_t0.bsnp")
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    p = subprocess.Popen(
        [GAME_BIN, "--rl-bin", "--render", "off", "--pace", "unlimited",
         "--seed", str(seed), "--mobs", "off"],
        stdin=subprocess.PIPE, stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL)
    try:
        _exact(p, BIN_SIZE)  # initial (tick 0) obs record
        act = {"snapshot": path, "snapshot_r": radius, "cam": 0}
        p.stdin.write((json.dumps(act) + "\n").encode())
        p.stdin.flush()
        _exact(p, BIN_SIZE)  # tick 1 record => pre-tick snapshot flushed
    finally:
        p.kill()
        p.wait()
    if strip_liquid:
        stripped = strip_snapshot_liquid(path)
        relight_snapshot(path, seed, radius)
        print(f"  seed {seed}: stripped {stripped} liquid cells for "
              "non-fluid parity fixture", flush=True)
    liquid, ncoal, vol = snap_liquid_flag(path)
    flag = "LIQUID" if liquid else "ok"
    print(f"  seed {seed}: {path} vol={vol} coal={ncoal} "
          f"size={os.path.getsize(path)} [{flag}]", flush=True)
    return (seed, "t0", path, flag)


def _filter_seeds(all_seeds, seeds_arg):
    if not seeds_arg:
        return list(all_seeds)
    keep = {int(s) for s in seeds_arg.split(",") if s.strip()}
    return [s for s in all_seeds if s in keep]


def main_t0(seeds_arg=None, snap_path=None, strip_liquid=False):
    os.makedirs(SNAPS, exist_ok=True)
    prefixes = json.load(open(os.path.join(OUT, "coal_prefixes.json")))
    seeds = _filter_seeds(sorted(int(s) for s in prefixes), seeds_arg)
    print(f"baking t0 snapshots (r={T0_R}) for {len(seeds)} seeds: {seeds}",
          flush=True)
    if snap_path and len(seeds) != 1:
        raise ValueError("--snap-path requires exactly one selected seed")
    rows = [bake_t0(s, path=snap_path, strip_liquid=strip_liquid)
            for s in seeds]
    nliquid = sum(r[3] == "LIQUID" for r in rows)
    print(f"\n{len(rows)} t0 snapshots written, {nliquid} liquid-flagged")


def bake_seed(seed, prefix):
    print(f"== seed {seed}: replaying prefix ({len(prefix)} ticks)",
          flush=True)
    env = make_env(seed, prefix)
    rows = []
    try:
        for d in STAGES:
            ok = cp.stage_coal(env, budget=BUDGET, stop_dist=d)
            if not ok:
                # cp.LAST_FAIL splits the two very different skips:
                # "scan-empty" (no coal in the obs window at all) vs
                # "budget-exhausted" (the burrow ran out of ticks).
                print(f"  seed {seed} d={d}: stage_coal FAILED "
                      f"({cp.LAST_FAIL})", flush=True)
                rows.append((seed, d, None, f"stage-failed:{cp.LAST_FAIL}"))
                continue
            if cp.inv(env, cp.IX_COAL) >= 1:
                print(f"  seed {seed} d={d}: burrow already mined the coal; "
                      f"snapshot skipped", flush=True)
                rows.append((seed, d, None, "already-mined"))
                continue
            quiesce(env)
            path = os.path.join(SNAPS, f"s{seed}_d{d}.bsnp")
            cp.step(env, {"snapshot": path, "snapshot_r": CURRICULUM_R,
                          "cam": 0})
            liquid, ncoal, _ = snap_liquid_flag(path)
            flag = "LIQUID" if liquid else "ok"
            print(f"  seed {seed} d={d}: {path} coal={ncoal} [{flag}]",
                  flush=True)
            rows.append((seed, d, path, flag))
    finally:
        env.proc.kill()
    return rows


def main(seeds_arg=None):
    global make_env, cp
    import chain_probe as cp
    make_env = cp.make_env
    os.makedirs(SNAPS, exist_ok=True)
    prefixes = json.load(open(os.path.join(OUT, "coal_prefixes.json")))
    seeds = _filter_seeds(sorted(int(s) for s in prefixes), seeds_arg)
    print(f"baking snapshots for {len(seeds)} seeds: {seeds}", flush=True)
    all_rows = []
    for s in seeds:
        all_rows += bake_seed(s, prefixes[str(s)])
    print("\n== summary ==")
    nliquid = 0
    for seed, d, path, flag in all_rows:
        print(f"seed {seed:3d} d={d}: "
              f"{os.path.basename(path) if path else '-':<18} {flag}")
        nliquid += flag == "LIQUID"
    written = sum(1 for r in all_rows if r[2])
    print(f"{written} snapshots written, {nliquid} liquid-flagged, "
          f"{len(all_rows) - written} skipped/failed")


def main_expand(seeds_arg=None, stages_sel=None):
    """--expand: re-dump existing .bsnp fixtures at CURRICULUM_R in place.

    Fixtures baked before 2026-08-07 use the rl_mode default radius 32, which
    is smaller than the camera reach (OC_FAR=48), so verify_cpu can only
    BLOCK on them (fixture camera envelope). This replays each file through
    magma --snapshot-in and re-dumps it with the larger radius: the inner
    cells are byte-identical (magma restored them) and the new shell is the
    same worldgen magma's camreg reads, so the cam compare becomes exact
    again. Cheaper and attrition-free vs re-running the curriculum bake.

    --expand [--seeds 14,27] [--stages-sel 6.0,4.5] [--curriculum-r 64]
    """
    seeds = None
    if seeds_arg:
        seeds = {int(s) for s in seeds_arg.split(",") if s.strip()}
    want = ([float(s) for s in stages_sel.split(",") if s.strip()]
            if stages_sel else list(STAGES))
    rows = []
    for name in sorted(os.listdir(SNAPS)):
        if not name.startswith("s") or not name.endswith(".bsnp"):
            continue
        stem = name[1:-5]
        if "_d" not in stem:
            continue          # t0 / iron fixtures already carry T0_R
        seed_text, stage_text = stem.split("_d", 1)
        try:
            seed, stage = int(seed_text), float(stage_text)
        except ValueError:
            continue
        if (seeds is not None and seed not in seeds) or stage not in want:
            continue
        path = os.path.join(SNAPS, name)
        before = read_region_dims(path)
        if before[3] >= 2 * CURRICULUM_R and before[5] >= 2 * CURRICULUM_R:
            print(f"  {name}: already {before[3]}x{before[4]}x{before[5]}, "
                  f"skipped", flush=True)
            continue
        relight_snapshot(path, seed, CURRICULUM_R)
        after = read_region_dims(path)
        print(f"  {name}: {before[3]}x{before[4]}x{before[5]} -> "
              f"{after[3]}x{after[4]}x{after[5]}", flush=True)
        rows.append(name)
    print(f"\n{len(rows)} fixtures re-dumped at radius {CURRICULUM_R}")


def read_region_dims(path):
    """(rx0, ry0, rz0, rnx, rny, rnz) from a .bsnp head."""
    with open(path, "rb") as f:
        head = f.read(HEAD_SIZE)
    return struct.unpack_from("<6i", head, RDIMS_OFF)


def read_snap_tick(path):
    """RlSnapHead.tick from a .bsnp (the dump tick)."""
    with open(path, "rb") as f:
        head = f.read(24)
    if len(head) < 24 or head[:4] != b"BSNP":
        raise RuntimeError(f"not a .bsnp: {path}")
    return struct.unpack_from("<q", head, 16)[0]


def stage_meta_path(path):
    if path.endswith(".bsnp"):
        return path[:-5] + ".meta.json"
    return path + ".meta.json"


def write_stage_meta(path, seed, k, first_idx, dump_tick, n_played):
    meta = {
        "seed": int(seed),
        "stage": int(k),
        "first_action_idx": int(first_idx),
        "dump_tick": int(dump_tick),
        "n_played": int(n_played),
        "n_quiesce": QUIESCE,
        "remainder_start": int(first_idx) + 1,
    }
    with open(stage_meta_path(path), "w") as f:
        json.dump(meta, f, indent=2)
        f.write("\n")
    return meta


def load_stage_meta(path):
    mp = stage_meta_path(path)
    if not os.path.isfile(mp):
        return None
    with open(mp) as f:
        return json.load(f)


def remainder_actions(played, start_idx, min_ticks=None):
    """Chain tail after start_idx, padded with no-ops to min_ticks."""
    if min_ticks is None:
        min_ticks = MIN_EMIT_TICKS
    rest = [_plain_act(a) for a in played[start_idx:]]
    n_chain = len(rest)
    if n_chain < min_ticks:
        rest = rest + [{"cam": 0} for _ in range(min_ticks - n_chain)]
    return rest, n_chain


def played_path_for(seed):
    return os.path.join(OUT, f"chain_played_s{seed}.json")


def save_stage_index(seed, first, played):
    os.makedirs(OUT, exist_ok=True)
    ppath = played_path_for(seed)
    with open(ppath, "w") as f:
        json.dump(played, f)
    data = {}
    if os.path.isfile(STAGE_INDEX):
        with open(STAGE_INDEX) as f:
            data = json.load(f)
    data[str(seed)] = {
        "first": {str(k): int(v) for k, v in first.items()},
        "n_played": len(played),
        "played_path": os.path.basename(ppath),
    }
    with open(STAGE_INDEX, "w") as f:
        json.dump(data, f, indent=2)
        f.write("\n")


def load_stage_index(seed):
    if not os.path.isfile(STAGE_INDEX):
        return None, None
    with open(STAGE_INDEX) as f:
        data = json.load(f)
    row = data.get(str(seed))
    if not row:
        return None, None
    ppath = os.path.join(OUT, row.get("played_path",
                                      os.path.basename(played_path_for(seed))))
    if not os.path.isfile(ppath):
        return None, None
    with open(ppath) as f:
        played = json.load(f)
    if len(played) != int(row.get("n_played", len(played))):
        return None, None
    first = {int(k): int(v) for k, v in row["first"].items()}
    return first, played


def locate_chain_stages(seed, actions):
    first, played = load_stage_index(seed)
    if first is not None:
        print(f"  seed {seed}: cached stage index first={first} "
              f"n_played={len(played)}", flush=True)
        return first, played
    first, played = find_chain_stage_idx(seed, actions)
    save_stage_index(seed, first, played)
    return first, played


def chain_stage_ok(inv, k):
    """True iff cr_stage_of_best's stage-k predicate holds on inv_counts[9]."""
    log = int(inv[cp.IX_LOG])
    plank = int(inv[cp.IX_PLANK])
    cobble = int(inv[cp.IX_COBBLE])
    wpick = int(inv[cp.IX_WPICK])
    coal = int(inv[cp.IX_COAL])
    if k == 1:
        return log >= 3 or plank >= 1
    if k == 2:
        return wpick >= 1
    if k == 3:
        return wpick >= 1 and cobble >= 3
    if k == 4:
        return coal >= 1
    raise ValueError(f"bad chain stage {k}")


def _plain_act(act):
    return {k: v for k, v in act.items()
            if k not in ("snapshot", "snapshot_r", "snapshot_bounds")}


def _kill_env(env):
    try:
        env.proc.kill()
        env.proc.wait()
    except Exception:
        pass


def _inv_brief(inv):
    return {cp.INV_IDS[i]: int(inv[i]) for i in range(9) if int(inv[i])}


def _walk_to_xz(env, x, z, budget=250):
    """Return toward (x,z) with jump so a water close-walk can climb out."""
    dist2 = 1e9
    for _ in range(budget):
        dx = x - env.obs["x"]
        dz = z - env.obs["z"]
        dist2 = dx * dx + dz * dz
        if dist2 < 0.64:
            return True
        tyaw = math.degrees(math.atan2(-dx, dz))
        a = cp.turn_act(cp.wrap180(tyaw - env.obs["yaw"]), 0)
        a["forward"] = 1
        a["jump"] = 1
        cp.step(env, a)
    return dist2 < 4.0


def _grab_coal(env, budget=30):
    """Face-adjacent burrow to the nearest scanned coal, then mine+collect.

    stage_coal only mines the ore at dist<=3.2 and otherwise tunnels; next to
    a vein (dist ~4) it can burn the budget mining in place. This walks a
    2-high axis-aligned corridor and mines at 4.5.
    """
    if not cp.select_hotbar(env, 270):
        return False
    for _ in range(budget):
        if cp.inv(env, cp.IX_COAL) >= 1:
            return True
        coal = [c for c in env.obs["coal"] if c != [0, 0, 0]]
        if not coal:
            return False
        px, py, pz = env.obs["x"], env.obs["y"], env.obs["z"]
        tx, ty, tz = min(
            coal,
            key=lambda c: (c[0] + 0.5 - px) ** 2
            + (c[1] + 0.5 - py - cp.EYE) ** 2
            + (c[2] + 0.5 - pz) ** 2)
        _, _, dist = cp.aim_error(env.obs, tx, ty, tz)
        if dist <= 4.5:
            cp.mine_block(env, tx, ty, tz, budget=160)
            cp.mine_block(env, tx, ty + 1, tz, budget=80)
            for _ in range(20):
                if cp.inv(env, cp.IX_COAL) >= 1:
                    return True
                ry, _, _ = cp.aim_error(env.obs, tx, ty, tz)
                a = cp.turn_act(ry, 0)
                a["forward"] = 1
                a["jump"] = 1
                cp.step(env, a)
            continue
        dx, dz = tx + 0.5 - px, tz + 0.5 - pz
        if abs(dx) >= abs(dz):
            cx = math.floor(px) + (1 if dx > 0 else -1)
            cz = math.floor(pz)
        else:
            cx = math.floor(px)
            cz = math.floor(pz) + (1 if dz > 0 else -1)
        feet = math.floor(py)
        cp.mine_block(env, cx, feet, cz, budget=100)
        cp.mine_block(env, cx, feet + 1, cz, budget=100)
        ry, _, _ = cp.aim_error(env.obs, cx, feet, cz)
        cp.step(env, cp.turn_act(ry, 0))
        for _ in range(8):
            cp.step(env, {"forward": 1, "jump": 1})
    return cp.inv(env, cp.IX_COAL) >= 1


def _close_gui(env):
    """Close an open container without leaving the player in water.

    close_container has to walk dist^2>36; that walk can enter a lake.
    Save xz, close, then walk back so stage_dig shafts on dry ground.
    """
    if env.obs["container"] == 0:
        return True
    hx, hz = env.obs["x"], env.obs["z"]
    ok = cp.close_container(env)
    _walk_to_xz(env, hx, hz)
    return ok and env.obs["container"] == 0


def obtain_chain_actions(seed):
    """Full spawn-to-torch action list, or (None, probe-failed reason).

    Seed 10 is the committed demonstration (chain_actions_s10.json). Every
    other seed is generated live by chain_probe.run_seed; a failed stage
    skips the seed rather than forcing a partial chain.
    """
    if seed == 10:
        path = os.path.join(OUT, "chain_actions_s10.json")
        if not os.path.isfile(path):
            return None, "probe-failed:missing-chain_actions_s10.json"
        acts = json.load(open(path))
        if not acts:
            return None, "probe-failed:empty-chain_actions_s10.json"
        return acts, None
    try:
        results, actions = cp.run_seed(seed, verbose=True)
    except Exception as e:
        return None, f"probe-failed:{type(e).__name__}:{e}"
    if not results:
        return None, "probe-failed:no-results"
    if not all(ok for _, ok, _ in results):
        name = next(n for n, ok, _ in results if not ok)
        return None, f"probe-failed:{name}"
    return list(actions), None


def _note_stages(seed, env, first):
    inv = env.obs["inv_counts"]
    i = len(env.actions) - 1
    for k in CHAIN_STAGE_KS:
        if k not in first and chain_stage_ok(inv, k):
            first[k] = i
            print(f"  seed {seed} stg{k}: first at action {i} "
                  f"t={env.obs['t']} inv={_inv_brief(inv)}",
                  flush=True)


def find_chain_stage_idx(seed, actions):
    """Replay with cam=0; return ({stage: first action index}, played acts).

    chain_actions_s10.json crafts the wooden pick with the table GUI still
    open (container=1 from that tick through the end of the file). Magma
    pins leftClickCounter while a container is up, so the recorded attack
    stream never breaks a block. If the open-loop replay misses later
    stages, close the GUI the same way chain_probe.stage_pick does, then
    run stage_dig / stage_coal so the first-satisfy ticks exist.
    """
    env = cp.MagmaEnv(seed)
    first = {}
    real_step = cp.step

    def stepped(e, act):
        r = real_step(e, act)
        _note_stages(seed, e, first)
        return r

    try:
        for act in actions:
            a = _plain_act(act)
            a["cam"] = 0
            real_step(env, a)
            _note_stages(seed, env, first)
            if len(first) == 4:
                break
            # chain_actions_s10.json keeps the table GUI open after craft:3
            # and then holds attack for ~1600 ticks. Those attacks no-op
            # (leftClickCounter pin) and spin the look. Stop and close.
            # run_seed recordings include close_container walks after the
            # pick; those must keep playing or later stages are thrown away.
            if (2 in first and 3 not in first and env.obs["container"]):
                rest = actions[len(env.actions):]
                nfwd = sum(1 for a in rest if a.get("forward"))
                if nfwd < 20:
                    print(f"  seed {seed}: stopping open-loop at action "
                          f"{len(env.actions) - 1} (GUI open, only {nfwd} "
                          f"forward ticks left)", flush=True)
                    break
        if len(first) < 4:
            print(f"  seed {seed}: sequence ended n={len(env.actions)} "
                  f"stages={sorted(first)} container={env.obs['container']} "
                  f"y={env.obs['y']:.2f} inv={_inv_brief(env.obs['inv_counts'])}",
                  flush=True)
            cp.step = stepped
            if env.obs["container"]:
                print(f"  seed {seed}: closing container "
                      f"(dig frozen while GUI is open)", flush=True)
                ok = _close_gui(env)
                print(f"  seed {seed}: close_gui "
                      f"{'OK' if ok else 'FAIL'} "
                      f"container={env.obs['container']} "
                      f"y={env.obs['y']:.2f}", flush=True)
            if 3 not in first:
                print(f"  seed {seed}: running stage_dig", flush=True)
                ok = cp.stage_dig(env)
                print(f"  seed {seed}: stage_dig {'OK' if ok else 'FAIL'} "
                      f"y={env.obs['y']:.2f} "
                      f"inv={_inv_brief(env.obs['inv_counts'])}", flush=True)
            if 4 not in first:
                visible = [c for c in env.obs["coal"] if c != [0, 0, 0]]
                if visible:
                    print(f"  seed {seed}: grabbing nearest coal "
                          f"(scan={len(visible)})", flush=True)
                    ok = _grab_coal(env)
                    print(f"  seed {seed}: grab_coal {'OK' if ok else 'FAIL'} "
                          f"y={env.obs['y']:.2f} "
                          f"inv={_inv_brief(env.obs['inv_counts'])}",
                          flush=True)
                else:
                    print(f"  seed {seed}: running stage_coal", flush=True)
                    ok = cp.stage_coal(env)
                    print(f"  seed {seed}: stage_coal "
                          f"{'OK' if ok else 'FAIL'} ({cp.LAST_FAIL}) "
                          f"y={env.obs['y']:.2f} "
                          f"inv={_inv_brief(env.obs['inv_counts'])}",
                          flush=True)
                    if 4 not in first:
                        print(f"  seed {seed}: grabbing nearest coal",
                              flush=True)
                        ok = _grab_coal(env)
                        print(f"  seed {seed}: grab_coal "
                              f"{'OK' if ok else 'FAIL'} "
                              f"y={env.obs['y']:.2f} "
                              f"inv={_inv_brief(env.obs['inv_counts'])}",
                              flush=True)
        played = [_plain_act(a) for a in env.actions]
        return first, played
    finally:
        cp.step = real_step
        _kill_env(env)


def dump_chain_stage(seed, actions, idx, k):
    """Replay prefix through first-satisfy, quiesce, dump s{seed}_stg{k}.bsnp.

    Census liquid is recorded, not an emit verdict. Sidecar persists dump_tick
    (also in the .bsnp header) and remainder_start = idx+1.
    """
    prefix = [_plain_act(a) for a in actions[:idx + 1]]
    env = make_env(seed, prefix)
    path = os.path.join(SNAPS, f"s{seed}_stg{k}.bsnp")
    try:
        inv = env.obs["inv_counts"]
        if not chain_stage_ok(inv, k):
            print(f"  seed {seed} stg{k}: prefix inv does not satisfy "
                  f"predicate inv={_inv_brief(inv)}", flush=True)
            return None, "dump-failed:predicate"
        if env.obs["container"]:
            # Snapshot with container!=0 is BP_REQ_UNREPRESENTED_SNAPSHOT
            # in blaze, and dig is frozen. Walk out of range, then return.
            print(f"  seed {seed} stg{k}: closing container before dump",
                  flush=True)
            if not _close_gui(env):
                print(f"  seed {seed} stg{k}: close_gui FAIL "
                      f"container={env.obs['container']}", flush=True)
        quiesce(env)
        cp.step(env, {"snapshot": path, "snapshot_r": CURRICULUM_R, "cam": 0})
        if not os.path.isfile(path):
            return None, "dump-failed:missing-file"
        dump_tick = read_snap_tick(path)
        write_stage_meta(path, seed, k, idx, dump_tick, len(actions))
        liquid, ncoal, vol = snap_liquid_flag(path)
        tag = "liquid" if liquid else "dry"
        print(f"  seed {seed} stg{k}: {path} vol={vol} coal={ncoal} "
              f"tick={dump_tick} first_idx={idx} size={os.path.getsize(path)} "
              f"[{tag}]", flush=True)
        return path, "ok"
    finally:
        _kill_env(env)


def ensure_blaze_cpu_so():
    if os.path.isfile(CPU_SO):
        return CPU_SO
    print(f"building {CPU_SO}", flush=True)
    subprocess.check_call(["make", "-C", MAGMA, "blaze_so"])
    if not os.path.isfile(CPU_SO):
        raise RuntimeError(f"blaze_cpu.so missing after make blaze_so: {CPU_SO}")
    return CPU_SO


def verify_chain_stage(path, k, n_ticks=10):
    """Load in blaze CPU env, reset one lane, step n_ticks, check predicate."""
    if ENV_DIR not in sys.path:
        sys.path.insert(0, ENV_DIR)
    from blaze import VecBlaze
    env = VecBlaze(1, so_path=CPU_SO)
    try:
        env.load_snapshots([path])
        env.assign([0])
        env.reset()
        act = np.zeros((1, 13), dtype=np.float64)
        act[0, 9] = -1.0
        act[0, 10] = -1.0
        for _ in range(n_ticks):
            env.step(act, repeat=1)
        inv = [int(x) for x in np.asarray(env.status[0, :9])]
        return chain_stage_ok(inv, k), inv
    finally:
        env.close()


def remainder_start_for(seed, k, path, first, played):
    dump_tick = read_snap_tick(path)
    meta = load_stage_meta(path)
    if meta is not None and int(meta.get("dump_tick", -1)) != int(dump_tick):
        print(f"  seed {seed} stg{k}: meta dump_tick={meta.get('dump_tick')} "
              f"!= header {dump_tick}; using locate first_idx", flush=True)
        meta = None
    if meta is not None and "remainder_start" in meta and played:
        start = int(meta["remainder_start"])
    elif k in first and played:
        start = int(first[k]) + 1
    else:
        # No reconstructed chain tail: idle no-op remainder (padded to 600).
        start = len(played)
    if start < 0:
        start = 0
    if start > len(played):
        print(f"  seed {seed} stg{k}: remainder_start {start} > "
              f"n_played {len(played)}; clamping", flush=True)
        start = len(played)
    return start, dump_tick, None


def verify_emit_stage(seed, k, path, played, first):
    """Parity + quiescence + inventory. Never emits on a failed predicate."""
    import verify_cpu as vc
    start, dump_tick, err = remainder_start_for(seed, k, path, first, played)
    if err:
        return err
    if load_stage_meta(path) is None:
        write_stage_meta(path, seed, k, start - 1, dump_tick, len(played))
    rest, n_chain = remainder_actions(played, start)
    print(f"  seed {seed} stg{k}: dump_tick={dump_tick} "
          f"remainder_start={start} chain_tail={n_chain} "
          f"replay_ticks={len(rest)}", flush=True)
    info = {}
    status = vc.run_seed_parity(
        seed, path, rest, f"stg{k} remainder x{len(rest)}",
        list(vc.PARITY_SUPPORTED),
        strict_capabilities=True,
        require_evidence=False,
        track_liquid=True,
        result=info)
    exact = info.get("exact_ticks", 0)
    first_div = info.get("first_div")
    print(f"  seed {seed} stg{k}: digest-equal ticks={exact}/{len(rest)} "
          f"parity={status} first_div={first_div} "
          f"liquid_n={info.get('liquid_n')} "
          f"liquid_changed_at={info.get('liquid_changed_at')}", flush=True)
    if info.get("error"):
        return "FLAGGED(probe-failed)"
    if status == vc.BLOCKED:
        return "FLAGGED(probe-failed)"
    if status != vc.VERIFIED:
        tick = first_div if first_div is not None else "?"
        return f"FLAGGED(parity-diverged@tick {tick})"
    if info.get("liquid_changed_at") is not None:
        return "FLAGGED(liquid-active)"
    try:
        ok, inv = verify_chain_stage(path, k)
    except Exception as e:
        print(f"  seed {seed} stg{k}: inventory verify raised "
              f"{type(e).__name__}:{e}", flush=True)
        return "FLAGGED(probe-failed)"
    if not ok:
        print(f"  seed {seed} stg{k}: inventory verify-failed "
              f"inv={_inv_brief(inv)}", flush=True)
        return "FLAGGED(probe-failed)"
    print(f"  seed {seed} stg{k}: inventory ok inv={_inv_brief(inv)}",
          flush=True)
    return "emitted"


def bake_chain_from_actions(seed, actions, bake=True, verify_emit=True):
    print(f"== seed {seed}: locating stage ticks ({len(actions)} actions)",
          flush=True)
    first, played = {}, []
    if actions:
        try:
            first, played = locate_chain_stages(seed, actions)
        except Exception as e:
            print(f"  seed {seed}: find failed {type(e).__name__}:{e}",
                  flush=True)
            first, played = {}, []
    else:
        cached = load_stage_index(seed)
        if cached[0] is not None:
            first, played = cached
            print(f"  seed {seed}: cached stage index first={first} "
                  f"n_played={len(played)}", flush=True)
        else:
            print(f"  seed {seed}: no chain actions; idle remainder on "
                  f"existing snaps", flush=True)
    rows = []
    for k in CHAIN_STAGE_KS:
        path = os.path.join(SNAPS, f"s{seed}_stg{k}.bsnp")
        if k not in first:
            print(f"  seed {seed} stg{k}: not-reached in this playthrough",
                  flush=True)
            if not os.path.isfile(path):
                rows.append((seed, k, None, "FLAGGED(probe-failed)"))
                continue
            print(f"  seed {seed} stg{k}: existing snap, idle remainder",
                  flush=True)
        if bake and not os.path.isfile(path):
            try:
                path, flag = dump_chain_stage(seed, played, first[k], k)
            except Exception as e:
                print(f"  seed {seed} stg{k}: dump failed "
                      f"{type(e).__name__}:{e}", flush=True)
                rows.append((seed, k, None, "FLAGGED(probe-failed)"))
                continue
            if flag != "ok" or not path:
                rows.append((seed, k, path, "FLAGGED(probe-failed)"))
                continue
        elif os.path.isfile(path):
            print(f"  seed {seed} stg{k}: existing {path} "
                  f"tick={read_snap_tick(path)}", flush=True)
            if load_stage_meta(path) is None:
                write_stage_meta(path, seed, k, first.get(k, -1),
                                 read_snap_tick(path), len(played))
        else:
            print(f"  seed {seed} stg{k}: missing {path}", flush=True)
            rows.append((seed, k, None, "FLAGGED(probe-failed)"))
            continue
        if not verify_emit:
            rows.append((seed, k, path, "dumped"))
            continue
        try:
            flag = verify_emit_stage(seed, k, path, played, first)
        except Exception as e:
            print(f"  seed {seed} stg{k}: emit raised "
                  f"{type(e).__name__}:{e}", flush=True)
            flag = "FLAGGED(probe-failed)"
        print(f"  seed {seed} stg{k}: {flag}", flush=True)
        rows.append((seed, k, path, flag))
    return rows


def chain_stage_seeds(seeds_arg):
    prefixes = json.load(open(os.path.join(OUT, "coal_prefixes.json")))
    default = [10] + [s for s in sorted(int(x) for x in prefixes) if s != 10]
    return _filter_seeds(default, seeds_arg)


def main_chain_stages(seeds_arg=None, bake=True, verify_emit=True):
    global make_env, cp
    import chain_probe as cp
    make_env = cp.make_env
    if not os.path.isfile(GAME_BIN):
        print(f"building {GAME_BIN}", flush=True)
        subprocess.check_call(["make", "-C", MAGMA, "game"])
    ensure_blaze_cpu_so()
    os.makedirs(SNAPS, exist_ok=True)
    seeds = chain_stage_seeds(seeds_arg)
    mode = []
    if bake:
        mode.append("bake")
    if verify_emit:
        mode.append("verify-emit")
    print(f"chain-stages ({'+'.join(mode) or 'index-only'}, r={CURRICULUM_R}) "
          f"for {len(seeds)} seeds: {seeds}", flush=True)

    actions_by_seed = {}
    errors_by_seed = {}

    def _obtain(s):
        first, played = load_stage_index(s)
        if first is not None and played:
            return s, (played, None)
        return s, obtain_chain_actions(s)

    workers = min(4, max(1, len(seeds)))
    with ThreadPoolExecutor(max_workers=workers) as pool:
        futs = [pool.submit(_obtain, s) for s in seeds]
        for fut in as_completed(futs):
            s, (acts, err) = fut.result()
            if err:
                print(f"  seed {s}: {err}", flush=True)
                errors_by_seed[s] = err
            else:
                print(f"  seed {s}: chain actions ready ({len(acts)} ticks)",
                      flush=True)
                actions_by_seed[s] = acts

    all_rows = []
    for s in seeds:
        if s in errors_by_seed:
            print(f"  seed {s}: {errors_by_seed[s]} (existing snaps still "
                  f"go through verify-emit)", flush=True)
            acts = actions_by_seed.get(s, [])
        else:
            acts = actions_by_seed[s]
        all_rows.extend(bake_chain_from_actions(
            s, acts, bake=bake, verify_emit=verify_emit))

    print("\n== chain-stages emit ==", flush=True)
    print(f"{'seed':>6} {'stg':>4} {'status':<42} path", flush=True)
    counts = {}
    for seed, k, path, flag in all_rows:
        key = flag.split("(", 1)[0] if flag.startswith("FLAGGED") else flag
        counts[key] = counts.get(key, 0) + 1
        print(f"{seed:6d} {k:4d} {flag:<42} {path or '-'}", flush=True)
    print("counts: " + " ".join(f"{k}={v}" for k, v in sorted(counts.items())),
          flush=True)


def parse_args(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--expand", action="store_true",
                    help="re-dump existing d* fixtures at --curriculum-r")
    ap.add_argument("--t0", action="store_true",
                    help="bake fresh-spawn tick-0 snapshots (s<seed>_t0.bsnp)")
    ap.add_argument("--chain-stages", action="store_true",
                    help="bake per-stage s<seed>_stgK.bsnp from full chain actions")
    ap.add_argument("--verify-emit", action="store_true",
                    help="parity+quiescence emit pass on existing s*_stgK.bsnp "
                         "(also runs after --chain-stages)")
    ap.add_argument("--t0-r", type=int, default=64,
                    help="region radius for t0 snapshots (default 64)")
    ap.add_argument("--curriculum-r", type=int, default=None,
                    help="region radius for curriculum dumps "
                         "(default: same as --t0-r)")
    ap.add_argument("--seeds", default=None,
                    help="comma-separated seed filter")
    ap.add_argument("--snap-path", default=None,
                    help="explicit output path (t0 mode, single seed only)")
    ap.add_argument("--stages-sel", default=None,
                    help="comma-separated stages for --expand "
                         "(default: 6.0,4.5,3.0)")
    ap.add_argument("--strip-liquid", action="store_true",
                    help="replace liquid cells with air after t0 bake")
    return ap.parse_args(argv)


if __name__ == "__main__":
    args = parse_args()
    T0_R = args.t0_r
    CURRICULUM_R = (args.curriculum_r if args.curriculum_r is not None
                    else T0_R)
    # Module-level names used by bake_* / main_expand.
    globals()["T0_R"] = T0_R
    globals()["CURRICULUM_R"] = CURRICULUM_R
    if args.expand:
        main_expand(seeds_arg=args.seeds, stages_sel=args.stages_sel)
    elif args.t0:
        main_t0(seeds_arg=args.seeds, snap_path=args.snap_path,
                strip_liquid=args.strip_liquid)
    elif args.chain_stages or args.verify_emit:
        main_chain_stages(seeds_arg=args.seeds,
                          bake=args.chain_stages,
                          verify_emit=True)
    else:
        main(seeds_arg=args.seeds)
