/* Minecraft 1.7.10 biome registry. Generated by netherite.oracle.BiomeTable
 * from the oracle (make -C oracle biomes-h); do not edit by hand. */
#ifndef NETHERITE_BIOMES_H
#define NETHERITE_BIOMES_H

/* getBiomeClass(): layers compare biomes by it; a mutation reports its base's class */
enum biome_class {
    CLS_OCEAN = 1,
    CLS_PLAINS = 2,
    CLS_DESERT = 3,
    CLS_HILLS = 4,
    CLS_FOREST = 5,
    CLS_TAIGA = 6,
    CLS_SWAMP = 7,
    CLS_RIVER = 8,
    CLS_HELL = 9,
    CLS_END = 10,
    CLS_SNOW = 11,
    CLS_MUSHROOMISLAND = 12,
    CLS_BEACH = 13,
    CLS_JUNGLE = 14,
    CLS_STONEBEACH = 15,
    CLS_SAVANNA = 16,
    CLS_MESA = 17,
};

enum temp_category { TEMP_OCEAN, TEMP_COLD, TEMP_MEDIUM, TEMP_WARM };

/* which func_150573_a (surface) the object runs; MUTATED delegates to base */
enum surface_kind { SURF_GENERIC, SURF_HILLS, SURF_TAIGA, SURF_SAVANNA_M, SURF_SWAMP, SURF_MESA, SURF_MUTATED };

struct biome_def {
    const char *name;
    unsigned char exists, cls, temp_cat, snow, mesa, lightning;  /* lightning: canSpawnLightningBolt() */
    short base;              /* mutation: the biome it mutates, else -1 */
    short object_id;         /* biomeID of the object in this slot: 161 aliases 160 in 1.7.10 */
    float root, variation;   /* minHeight, maxHeight */
    float temperature, rainfall;
    unsigned short top, top_meta, filler;  /* filler is always placed with meta 0 */
    unsigned char surface;   /* enum surface_kind */
    unsigned char p1, p2;    /* hills: type; taiga: type; mesa: bryce, forest */
};

extern const struct biome_def BIOMES[256];

#endif
