/* Minecraft 1.7.10 block registry: the static properties world population,
 * block interaction and player physics read. Generated by
 * netherite.oracle.BlockTable from the oracle (make -C oracle blocks-h);
 * do not edit by hand. */
#ifndef NETHERITE_BLOCKS_H
#define NETHERITE_BLOCKS_H

/* one entry per distinct Material object a registered block uses */
struct material_def {
    const char *name;
    unsigned char is_liquid, is_solid, blocks_movement, can_burn, replaceable;
    unsigned char is_opaque, tool_not_required;
    unsigned char mobility;  /* getMaterialMobility(): 0 free, 1 no push, 2 immovable */
};

extern const struct material_def MATERIALS[33];

struct block_def {
    const char *name;
    unsigned char exists;    /* a block object is registered at this id */
    unsigned char opacity;   /* getLightOpacity(), 0..255 */
    unsigned char light;     /* getLightValue(), 0..15 */

    const char *class_name;  /* getClass().getSimpleName(), to switch behavior on */
    float hardness;          /* blockHardness, -1 is unbreakable */
    float resistance;        /* blockResistance as stored (setResistance multiplies by 3) */
    float slipperiness;      /* blockParticleGravity is separate; 0.6 unless ice */
    float particle_gravity;  /* blockParticleGravity, the dig particles' fall pull */

    unsigned char material;      /* index into MATERIALS */
    unsigned char opaque_cube;   /* isOpaqueCube() */
    unsigned char normal_block;  /* renderAsNormalBlock() */
    unsigned char normal_cube;   /* isNormalCube() */
    unsigned char tick_randomly; /* getTickRandomly() */
    unsigned char provides_power;/* canProvidePower() */
    unsigned char tile_entity;   /* instanceof ITileEntityProvider */
    unsigned char collidable;    /* isCollidable() */
    unsigned char render_type;   /* getRenderType() */

    double min_x, min_y, min_z, max_x, max_y, max_z;  /* setBlockBounds at construction */
};

extern const struct block_def BLOCKS[4096];

/* BlockFire.func_149844_e: per block id, can the fire renderer draw a
 * side or top quad against this block (> 0 when it can catch fire) */
extern const unsigned char FIRE_FLAM[4096];

#endif
