/* Minecraft 1.7.10 enchantment registry: what buildEnchantmentList in
 * EnchantmentHelper reads. Generated by netherite.oracle.EnchantTable from the
 * oracle (java -cp out/java/classes:... netherite.oracle.EnchantTable
 * csrc/engine/enchants.h); do not edit by hand. */
#ifndef NETHERITE_ENCHANTS_H
#define NETHERITE_ENCHANTS_H

/* EnumEnchantmentType, in declaration order; a type's canEnchantItem is
 * ported in enchant.c, since it switches on ItemSword/ItemTool/ItemBow; the
 * type table here is the ordinal each entry carries. */
enum enchant_type { E_ALL, E_ARMOR, E_ARMOR_FEET, E_ARMOR_LEGS, E_ARMOR_TORSO, E_ARMOR_HEAD, E_WEAPON, E_DIGGER, E_FISHING_ROD, E_BREAKABLE, E_BOW };

struct enchantment_def {
    unsigned short effect_id;
    unsigned char weight, min_level, max_level, type;
    const char *name;
    unsigned char min_enchantability[5];  /* levels 1..maxLevel */
    unsigned char max_enchantability[5];
};

static const struct enchantment_def ENCHANTS[24] = {
    {0, 10, 1, 4, E_ARMOR, "enchantment.protect.all", {1, 12, 23, 34, 0}, {21, 32, 43, 54, 0}},
    {1, 5, 1, 4, E_ARMOR, "enchantment.protect.fire", {10, 18, 26, 34, 0}, {22, 30, 38, 46, 0}},
    {2, 5, 1, 4, E_ARMOR_FEET, "enchantment.protect.fall", {5, 11, 17, 23, 0}, {15, 21, 27, 33, 0}},
    {3, 2, 1, 4, E_ARMOR, "enchantment.protect.explosion", {5, 13, 21, 29, 0}, {17, 25, 33, 41, 0}},
    {4, 5, 1, 4, E_ARMOR, "enchantment.protect.projectile", {3, 9, 15, 21, 0}, {18, 24, 30, 36, 0}},
    {5, 2, 1, 3, E_ARMOR_HEAD, "enchantment.oxygen", {10, 20, 30, 0, 0}, {40, 50, 60, 0, 0}},
    {6, 2, 1, 1, E_ARMOR_HEAD, "enchantment.waterWorker", {1, 0, 0, 0, 0}, {41, 0, 0, 0, 0}},
    {7, 1, 1, 3, E_ARMOR_TORSO, "enchantment.thorns", {10, 30, 50, 0, 0}, {61, 71, 81, 0, 0}},
    {16, 10, 1, 5, E_WEAPON, "enchantment.damage.all", {1, 12, 23, 34, 45}, {21, 32, 43, 54, 65}},
    {17, 5, 1, 5, E_WEAPON, "enchantment.damage.undead", {5, 13, 21, 29, 37}, {25, 33, 41, 49, 57}},
    {18, 5, 1, 5, E_WEAPON, "enchantment.damage.arthropods", {5, 13, 21, 29, 37}, {25, 33, 41, 49, 57}},
    {19, 5, 1, 2, E_WEAPON, "enchantment.knockback", {5, 25, 0, 0, 0}, {61, 71, 0, 0, 0}},
    {20, 2, 1, 2, E_WEAPON, "enchantment.fire", {10, 30, 0, 0, 0}, {61, 71, 0, 0, 0}},
    {21, 2, 1, 3, E_WEAPON, "enchantment.lootBonus", {15, 24, 33, 0, 0}, {61, 71, 81, 0, 0}},
    {32, 10, 1, 5, E_DIGGER, "enchantment.digging", {1, 11, 21, 31, 41}, {61, 71, 81, 91, 101}},
    {33, 1, 1, 1, E_DIGGER, "enchantment.untouching", {15, 0, 0, 0, 0}, {61, 0, 0, 0, 0}},
    {34, 5, 1, 3, E_BREAKABLE, "enchantment.durability", {5, 13, 21, 0, 0}, {61, 71, 81, 0, 0}},
    {35, 2, 1, 3, E_DIGGER, "enchantment.lootBonusDigger", {15, 24, 33, 0, 0}, {61, 71, 81, 0, 0}},
    {48, 10, 1, 5, E_BOW, "enchantment.arrowDamage", {1, 11, 21, 31, 41}, {16, 26, 36, 46, 56}},
    {49, 2, 1, 2, E_BOW, "enchantment.arrowKnockback", {12, 32, 0, 0, 0}, {37, 57, 0, 0, 0}},
    {50, 2, 1, 1, E_BOW, "enchantment.arrowFire", {20, 0, 0, 0, 0}, {50, 0, 0, 0, 0}},
    {51, 1, 1, 1, E_BOW, "enchantment.arrowInfinite", {20, 0, 0, 0, 0}, {50, 0, 0, 0, 0}},
    {61, 2, 1, 3, E_FISHING_ROD, "enchantment.lootBonusFishing", {15, 24, 33, 0, 0}, {61, 71, 81, 0, 0}},
    {62, 2, 1, 3, E_FISHING_ROD, "enchantment.fishingSpeed", {15, 24, 33, 0, 0}, {61, 71, 81, 0, 0}},
};

/* canApplyTogether(a, b) as a bitmask: bit j of CAN_APPLY_TOGETHER[i] is
 * ENCHANTS[i].canApplyTogether(ENCHANTS[j]). The relation is NOT symmetric:
 * lootBonus refuses silkTouch while silkTouch refuses only fortune.
 * buildEnchantmentList calls it as existing.canApplyTogether(candidate), so
 * the port must read this table in that direction. */

static const unsigned int CAN_APPLY_TOGETHER[24] = {
    0x00ffffe4u,
    0x00ffffe4u,
    0x00fffffbu,
    0x00ffffe4u,
    0x00ffffe4u,
    0x00ffffdfu,
    0x00ffffbfu,
    0x00ffff7fu,
    0x00fff8ffu,
    0x00fff8ffu,
    0x00fff8ffu,
    0x00fff7ffu,
    0x00ffefffu,
    0x00ff5fffu,
    0x00ffbfffu,
    0x00fd7fffu,
    0x00feffffu,
    0x00fd7fffu,
    0x00fbffffu,
    0x00f7ffffu,
    0x00efffffu,
    0x00dfffffu,
    0x00bf7fffu,
    0x007fffffu,
};

#endif
