/* Minecraft 1.7.10 item registry: the static item properties block interaction
 * and player physics read. Generated by netherite.oracle.ItemTable from the
 * oracle (make -C oracle items-h); do not edit by hand. */
#ifndef NETHERITE_ITEMS_H
#define NETHERITE_ITEMS_H

/* what an item is: only one of these carries each kind's fields */
enum item_kind { ITEM_PLAIN, ITEM_BLOCK, ITEM_TOOL, ITEM_SWORD, ITEM_FOOD, ITEM_ARMOR };

/* Item.ToolMaterial, in declaration order */
struct tool_material_def {
    const char *name;
    unsigned char harvest_level, enchantability;
    unsigned short max_uses;
    float efficiency, damage;  /* efficiencyOnProperMaterial, damageVsEntity */
};

extern const struct tool_material_def TOOL_MATERIALS[5];

struct item_def {
    const char *name;        /* registry name: a block's name for an ItemBlock */
    const char *class_name;  /* getClass().getSimpleName(), to switch behavior on */
    unsigned char exists;    /* an item object is registered at this id */
    unsigned char kind;      /* enum item_kind */
    unsigned char max_stack_size;
    unsigned short max_damage;   /* getMaxDamage() */
    unsigned char has_subtypes;
    short block_id;               /* ItemBlock: the block it places, else -1 */
    unsigned char tool_material;  /* ItemTool/ItemSword: TOOL_MATERIALS index, else 0 */
    float efficiency;             /* ItemTool: efficiencyOnProperMaterial, else 0 */
    float damage;                 /* ItemTool: damageVsEntity; ItemSword: attack damage, else 0 */
    unsigned char heal_amount;    /* ItemFood: healAmount, else 0 */
    float saturation;             /* ItemFood: saturationModifier, else 0 */
    unsigned char wolfs_meat;     /* ItemFood: isWolfsFavoriteMeat */
    unsigned char always_edible;  /* ItemFood: alwaysEdible */
    unsigned char armor_type;     /* ItemArmor: 0 helmet, 1 chest, 2 legs, 3 boots */
    unsigned char damage_reduce;  /* ItemArmor: damageReduceAmount */
};

extern const struct item_def ITEMS[4096];

#endif
