/* Minecraft 1.7.10 chest loot tables: every WeightedRandomChestContent array a
 * structure chest or dispenser draws from. Generated by netherite.oracle.LootProbe
 * from the oracle (make run CLASS=LootProbe CMD='{"header":"..."}'); do not edit
 * by hand. A row's book_enchantability is -1 for a plain entry and 30 for the
 * book entry each structure appends through func_92080_a; book_min/book_max/
 * book_weight are func_92112_a's arguments, 1/1/1 for func_92114_b. Item ids
 * are the ones in items.h. */
#ifndef NETHERITE_LOOT_TABLES_H
#define NETHERITE_LOOT_TABLES_H

#include "loot.h"

/* dungeon: generateChestContents(rand, func_92080_a(dungeonTable, book(func_92114_b(rand))), inv27, 8) */
static const struct loot_entry LOOT_DUNGEON[] = {
    {329, 0, 1, 1, 10, -1, 0, 0, 0},
    {265, 0, 1, 4, 10, -1, 0, 0, 0},
    {297, 0, 1, 1, 10, -1, 0, 0, 0},
    {296, 0, 1, 4, 10, -1, 0, 0, 0},
    {289, 0, 1, 4, 10, -1, 0, 0, 0},
    {287, 0, 1, 4, 10, -1, 0, 0, 0},
    {325, 0, 1, 1, 10, -1, 0, 0, 0},
    {322, 0, 1, 1, 1, -1, 0, 0, 0},
    {331, 0, 1, 4, 10, -1, 0, 0, 0},
    {2256, 0, 1, 1, 10, -1, 0, 0, 0},
    {2257, 0, 1, 1, 10, -1, 0, 0, 0},
    {421, 0, 1, 1, 10, -1, 0, 0, 0},
    {418, 0, 1, 1, 2, -1, 0, 0, 0},
    {417, 0, 1, 1, 5, -1, 0, 0, 0},
    {419, 0, 1, 1, 1, -1, 0, 0, 0},
    {403, 0, 1, 1, 1, 30, 1, 1, 1},
};

/* mineshaftCorridor: generateChestContents(rand, func_92080_a(mineshaftChestContents, book(func_92114_b(rand))), inv27, 3 + rand.nextInt(4)) */
static const struct loot_entry LOOT_MINESHAFT_CORRIDOR[] = {
    {265, 0, 1, 5, 10, -1, 0, 0, 0},
    {266, 0, 1, 3, 5, -1, 0, 0, 0},
    {331, 0, 4, 9, 5, -1, 0, 0, 0},
    {351, 4, 4, 9, 5, -1, 0, 0, 0},
    {264, 0, 1, 2, 3, -1, 0, 0, 0},
    {263, 0, 3, 8, 10, -1, 0, 0, 0},
    {297, 0, 1, 3, 15, -1, 0, 0, 0},
    {257, 0, 1, 1, 1, -1, 0, 0, 0},
    {66, 0, 4, 8, 1, -1, 0, 0, 0},
    {362, 0, 2, 4, 10, -1, 0, 0, 0},
    {361, 0, 2, 4, 10, -1, 0, 0, 0},
    {329, 0, 1, 1, 3, -1, 0, 0, 0},
    {417, 0, 1, 1, 1, -1, 0, 0, 0},
    {403, 0, 1, 1, 1, 30, 1, 1, 1},
};

/* strongholdCorridor: generateChestContents(rand, func_92080_a(strongholdChestContents, book(func_92114_b(rand))), inv27, 2 + rand.nextInt(2)) */
static const struct loot_entry LOOT_STRONGHOLD_CORRIDOR[] = {
    {368, 0, 1, 1, 10, -1, 0, 0, 0},
    {264, 0, 1, 3, 3, -1, 0, 0, 0},
    {265, 0, 1, 5, 10, -1, 0, 0, 0},
    {266, 0, 1, 3, 5, -1, 0, 0, 0},
    {331, 0, 4, 9, 5, -1, 0, 0, 0},
    {297, 0, 1, 3, 15, -1, 0, 0, 0},
    {260, 0, 1, 3, 15, -1, 0, 0, 0},
    {257, 0, 1, 1, 5, -1, 0, 0, 0},
    {267, 0, 1, 1, 5, -1, 0, 0, 0},
    {307, 0, 1, 1, 5, -1, 0, 0, 0},
    {306, 0, 1, 1, 5, -1, 0, 0, 0},
    {308, 0, 1, 1, 5, -1, 0, 0, 0},
    {309, 0, 1, 1, 5, -1, 0, 0, 0},
    {322, 0, 1, 1, 1, -1, 0, 0, 0},
    {329, 0, 1, 1, 1, -1, 0, 0, 0},
    {417, 0, 1, 1, 1, -1, 0, 0, 0},
    {418, 0, 1, 1, 1, -1, 0, 0, 0},
    {419, 0, 1, 1, 1, -1, 0, 0, 0},
    {403, 0, 1, 1, 1, 30, 1, 1, 1},
};

/* strongholdLibrary: generateChestContents(rand, func_92080_a(strongholdLibraryChestContents, book(func_92112_a(rand,1,5,2))), inv27, 1 + rand.nextInt(4)) */
static const struct loot_entry LOOT_STRONGHOLD_LIBRARY[] = {
    {340, 0, 1, 3, 20, -1, 0, 0, 0},
    {339, 0, 2, 7, 20, -1, 0, 0, 0},
    {395, 0, 1, 1, 1, -1, 0, 0, 0},
    {345, 0, 1, 1, 1, -1, 0, 0, 0},
    {403, 0, 1, 5, 2, 30, 1, 5, 2},
};

/* strongholdCrossing: generateChestContents(rand, func_92080_a(strongholdRoomCrossingChestContents, book(func_92114_b(rand))), inv27, 1 + rand.nextInt(4)) */
static const struct loot_entry LOOT_STRONGHOLD_CROSSING[] = {
    {265, 0, 1, 5, 10, -1, 0, 0, 0},
    {266, 0, 1, 3, 5, -1, 0, 0, 0},
    {331, 0, 4, 9, 5, -1, 0, 0, 0},
    {263, 0, 3, 8, 10, -1, 0, 0, 0},
    {297, 0, 1, 3, 15, -1, 0, 0, 0},
    {260, 0, 1, 3, 15, -1, 0, 0, 0},
    {257, 0, 1, 1, 1, -1, 0, 0, 0},
    {403, 0, 1, 1, 1, 30, 1, 1, 1},
};

/* desertTemple: generateChestContents(rand, func_92080_a(itemsToGenerateInTemple, book(func_92114_b(rand))), inv27, 2 + rand.nextInt(5)) */
static const struct loot_entry LOOT_DESERT_TEMPLE[] = {
    {264, 0, 1, 3, 3, -1, 0, 0, 0},
    {265, 0, 1, 5, 10, -1, 0, 0, 0},
    {266, 0, 2, 7, 15, -1, 0, 0, 0},
    {388, 0, 1, 3, 2, -1, 0, 0, 0},
    {352, 0, 4, 6, 20, -1, 0, 0, 0},
    {367, 0, 3, 7, 16, -1, 0, 0, 0},
    {329, 0, 1, 1, 3, -1, 0, 0, 0},
    {417, 0, 1, 1, 1, -1, 0, 0, 0},
    {418, 0, 1, 1, 1, -1, 0, 0, 0},
    {419, 0, 1, 1, 1, -1, 0, 0, 0},
    {403, 0, 1, 1, 1, 30, 1, 1, 1},
};

/* jungleTemple: generateChestContents(rand, func_92080_a(junglePyramidsChestContents, book(func_92114_b(rand))), inv27, 2 + rand.nextInt(5)) */
static const struct loot_entry LOOT_JUNGLE_TEMPLE[] = {
    {264, 0, 1, 3, 3, -1, 0, 0, 0},
    {265, 0, 1, 5, 10, -1, 0, 0, 0},
    {266, 0, 2, 7, 15, -1, 0, 0, 0},
    {388, 0, 1, 3, 2, -1, 0, 0, 0},
    {352, 0, 4, 6, 20, -1, 0, 0, 0},
    {367, 0, 3, 7, 16, -1, 0, 0, 0},
    {329, 0, 1, 1, 3, -1, 0, 0, 0},
    {417, 0, 1, 1, 1, -1, 0, 0, 0},
    {418, 0, 1, 1, 1, -1, 0, 0, 0},
    {419, 0, 1, 1, 1, -1, 0, 0, 0},
    {403, 0, 1, 1, 1, 30, 1, 1, 1},
};

/* jungleDispenser: func_150706_a(rand, junglePyramidsDispenserContents, dispenser9, 2) */
static const struct loot_entry LOOT_JUNGLE_DISPENSER[] = {
    {262, 0, 2, 7, 30, -1, 0, 0, 0},
};

/* blacksmith: generateChestContents(rand, villageBlacksmithChestContents, inv27, 3 + rand.nextInt(6)) */
static const struct loot_entry LOOT_BLACKSMITH[] = {
    {264, 0, 1, 3, 3, -1, 0, 0, 0},
    {265, 0, 1, 5, 10, -1, 0, 0, 0},
    {266, 0, 1, 3, 5, -1, 0, 0, 0},
    {297, 0, 1, 3, 15, -1, 0, 0, 0},
    {260, 0, 1, 3, 15, -1, 0, 0, 0},
    {257, 0, 1, 1, 5, -1, 0, 0, 0},
    {267, 0, 1, 1, 5, -1, 0, 0, 0},
    {307, 0, 1, 1, 5, -1, 0, 0, 0},
    {306, 0, 1, 1, 5, -1, 0, 0, 0},
    {308, 0, 1, 1, 5, -1, 0, 0, 0},
    {309, 0, 1, 1, 5, -1, 0, 0, 0},
    {49, 0, 3, 7, 5, -1, 0, 0, 0},
    {6, 0, 3, 7, 5, -1, 0, 0, 0},
    {329, 0, 1, 1, 3, -1, 0, 0, 0},
    {417, 0, 1, 1, 1, -1, 0, 0, 0},
    {418, 0, 1, 1, 1, -1, 0, 0, 0},
    {419, 0, 1, 1, 1, -1, 0, 0, 0},
};

/* netherBridge: generateChestContents(rand, field_111019_a, inv27, 2 + rand.nextInt(4)) */
static const struct loot_entry LOOT_NETHER_BRIDGE[] = {
    {264, 0, 1, 3, 5, -1, 0, 0, 0},
    {265, 0, 1, 5, 5, -1, 0, 0, 0},
    {266, 0, 1, 3, 15, -1, 0, 0, 0},
    {283, 0, 1, 1, 5, -1, 0, 0, 0},
    {315, 0, 1, 1, 5, -1, 0, 0, 0},
    {259, 0, 1, 1, 5, -1, 0, 0, 0},
    {372, 0, 3, 7, 5, -1, 0, 0, 0},
    {329, 0, 1, 1, 10, -1, 0, 0, 0},
    {418, 0, 1, 1, 8, -1, 0, 0, 0},
    {417, 0, 1, 1, 5, -1, 0, 0, 0},
    {419, 0, 1, 1, 3, -1, 0, 0, 0},
};

/* bonusChest: generateChestContents(rand, bonusChestContent, inv27, 10) */
static const struct loot_entry LOOT_BONUS_CHEST[] = {
    {280, 0, 1, 3, 10, -1, 0, 0, 0},
    {5, 0, 1, 3, 10, -1, 0, 0, 0},
    {17, 0, 1, 3, 10, -1, 0, 0, 0},
    {275, 0, 1, 1, 3, -1, 0, 0, 0},
    {271, 0, 1, 1, 5, -1, 0, 0, 0},
    {274, 0, 1, 1, 3, -1, 0, 0, 0},
    {270, 0, 1, 1, 5, -1, 0, 0, 0},
    {260, 0, 2, 3, 5, -1, 0, 0, 0},
    {297, 0, 2, 3, 3, -1, 0, 0, 0},
    {162, 0, 1, 3, 10, -1, 0, 0, 0},
};

static const struct loot_table LOOT_TABLES[] = {
    {"dungeon", LOOT_DUNGEON, (int)(sizeof LOOT_DUNGEON / sizeof LOOT_DUNGEON[0])},
    {"mineshaftCorridor", LOOT_MINESHAFT_CORRIDOR, (int)(sizeof LOOT_MINESHAFT_CORRIDOR / sizeof LOOT_MINESHAFT_CORRIDOR[0])},
    {"strongholdCorridor", LOOT_STRONGHOLD_CORRIDOR, (int)(sizeof LOOT_STRONGHOLD_CORRIDOR / sizeof LOOT_STRONGHOLD_CORRIDOR[0])},
    {"strongholdLibrary", LOOT_STRONGHOLD_LIBRARY, (int)(sizeof LOOT_STRONGHOLD_LIBRARY / sizeof LOOT_STRONGHOLD_LIBRARY[0])},
    {"strongholdCrossing", LOOT_STRONGHOLD_CROSSING, (int)(sizeof LOOT_STRONGHOLD_CROSSING / sizeof LOOT_STRONGHOLD_CROSSING[0])},
    {"desertTemple", LOOT_DESERT_TEMPLE, (int)(sizeof LOOT_DESERT_TEMPLE / sizeof LOOT_DESERT_TEMPLE[0])},
    {"jungleTemple", LOOT_JUNGLE_TEMPLE, (int)(sizeof LOOT_JUNGLE_TEMPLE / sizeof LOOT_JUNGLE_TEMPLE[0])},
    {"jungleDispenser", LOOT_JUNGLE_DISPENSER, (int)(sizeof LOOT_JUNGLE_DISPENSER / sizeof LOOT_JUNGLE_DISPENSER[0])},
    {"blacksmith", LOOT_BLACKSMITH, (int)(sizeof LOOT_BLACKSMITH / sizeof LOOT_BLACKSMITH[0])},
    {"netherBridge", LOOT_NETHER_BRIDGE, (int)(sizeof LOOT_NETHER_BRIDGE / sizeof LOOT_NETHER_BRIDGE[0])},
    {"bonusChest", LOOT_BONUS_CHEST, (int)(sizeof LOOT_BONUS_CHEST / sizeof LOOT_BONUS_CHEST[0])},
};

/* Every table, NULL-terminated, for a caller that wants to walk them all. */
#define LOOT_TABLES_ALL \
    &LOOT_TABLES[0], \
    &LOOT_TABLES[1], \
    &LOOT_TABLES[2], \
    &LOOT_TABLES[3], \
    &LOOT_TABLES[4], \
    &LOOT_TABLES[5], \
    &LOOT_TABLES[6], \
    &LOOT_TABLES[7], \
    &LOOT_TABLES[8], \
    &LOOT_TABLES[9], \
    &LOOT_TABLES[10], \
    NULL

#endif
