#!/usr/bin/env python3
"""Generate the AoS staging record for ENT-09's cold living pages."""

from __future__ import annotations

import argparse
import pathlib

from living_capacity_census import ROOT, living_fields


OUTPUT = ROOT / "magma" / "game" / "living_cold_slot.generated.h"
CORE_FIELDS = (
    ("u8", "store_type"), ("u8", "store_alive"),
    ("i32", "store_id"),
    ("double", "store_x"), ("double", "store_y"),
    ("double", "store_z"), ("double", "store_vx"),
    ("double", "store_vy"), ("double", "store_vz"),
    ("float", "store_yaw"), ("float", "store_health"),
    ("u8", "store_on_ground"), ("u32", "store_ai_state"),
    ("i32", "store_attack_time"), ("i32", "store_repath_timer"),
    ("double", "store_path_tx"), ("double", "store_path_ty"),
    ("double", "store_path_tz"), ("u32", "store_path_len"),
    ("i32", "store_cx"), ("i32", "store_cz"),
)
STORE_MAP = tuple((name.removeprefix("store_"), name)
                  for _, name in CORE_FIELDS)


def generated_text() -> str:
    fields = living_fields()
    lines = [
        "/* Generated by verify/completeness/generate_living_cold_slot.py.",
        " * Do not edit by hand. */",
        "#ifndef MAGMA_GAME_LIVING_COLD_SLOT_GENERATED_H",
        "#define MAGMA_GAME_LIVING_COLD_SLOT_GENERATED_H",
        "",
        "#include <string.h>",
        "",
        "typedef struct GmLivingColdSlot {",
    ]
    lines.extend(f"    {kind} {name};" for kind, name in CORE_FIELDS)
    for field in fields:
        tail = field["tail_dimensions"]
        lines.append(
            f"    {field['type']} {field['name']}{tail};")
    lines.extend([
        "} GmLivingColdSlot;",
        "",
        "static inline void gm_living_cold_from_store(",
        "        GmLivingColdSlot *dst, const GmMobLive *src,",
        "        const EwStore *store, int slot) {",
    ])
    for source, target in STORE_MAP:
        lines.append(f"    dst->{target} = store->{source}[slot];")
    for field in fields:
        name = field["name"]
        if field["tail_dimensions"]:
            lines.append(
                f"    memcpy(&dst->{name}, &src->{name}[slot], "
                f"sizeof dst->{name});")
        else:
            lines.append(f"    dst->{name} = src->{name}[slot];")
    lines.extend([
        "}",
        "",
        "static inline void gm_living_cold_from_hot(",
        "        GmLivingColdSlot *dst, const GmMobLive *src, int slot) {",
        "    const EwStore *store = src->current ? &src->b : &src->a;",
        "    gm_living_cold_from_store(dst, src, store, slot);",
        "}",
        "",
        "static inline void gm_living_cold_to_store(",
        "        GmMobLive *dst, EwStore *store, int slot,",
        "        const GmLivingColdSlot *src) {",
    ])
    for target, source in STORE_MAP:
        lines.append(f"    store->{target}[slot] = src->{source};")
    for field in fields:
        name = field["name"]
        if field["tail_dimensions"]:
            lines.append(
                f"    memcpy(&dst->{name}[slot], &src->{name}, "
                f"sizeof src->{name});")
        else:
            lines.append(f"    dst->{name}[slot] = src->{name};")
    lines.extend([
        "}",
        "",
        "static inline void gm_living_cold_to_hot(",
        "        GmMobLive *dst, int slot, const GmLivingColdSlot *src) {",
        "    EwStore *store = dst->current ? &dst->b : &dst->a;",
        "    gm_living_cold_to_store(dst, store, slot, src);",
        "}",
        "",
        "#endif", "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = generated_text()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != expected:
            print(f"FAIL stale generated living cold slot: {OUTPUT}")
            return 1
        print("PASS generated living cold slot is current")
        return 0
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
