/* batch_region_tensor: the RL/render BUDGET layer -- a BATCH of B independent block
 * tensors, each a dense region generated by rt_fill (region_tensor.h) from its own
 * (seed, origin). CPU generates the B envs sequentially; CUDA runs one thread PER ENV
 * in parallel, each thread with its own primer/scratch. Output is dumped element-wise
 * (%04x, env by env, index order) so runner.py's line diff is a literal ELEMENT-WISE
 * CPU==CUDA check over every block of every env.
 *
 * Pure in the env table: rt_fill is a pure function of (seed,origin,dims), so the whole
 * batch is bitwise-reproducible on CPU and CUDA. Shared region dims across all envs keep
 * the output layout regular: out_all[e*BRT_VOL + (ix*NY+iy)*NZ + iz]. */
#ifndef MC_BATCH_REGION_TENSOR_H
#define MC_BATCH_REGION_TENSOR_H

#include "region_tensor.h"   /* rt_fill, rt_count, rt_floordiv16 + chunk_provider types */

#define BRT_N   8            /* number of envs in the batch */
#define BRT_NX  24           /* shared region dims (x,y,z) */
#define BRT_NY  16
#define BRT_NZ  24
#define BRT_VOL (BRT_NX * BRT_NY * BRT_NZ)   /* 9216 u16 blocks per env */

typedef struct {
    i64 seed;
    int x0, y0, z0;   /* world-space origin of this env's region */
} BrtEnv;

/* Fixed env table: distinct seeds and origins (incl. negatives / chunk-straddling). */
static const BrtEnv BRT_ENVS[BRT_N] = {
    {12345LL,        0,  0,    0},
    {0LL,           16, 60,   16},
    {7LL,          -32, 40,  100},
    {42LL,         200, 50, -200},
    {2024LL,       -80, 70,  -80},
    {99LL,          48, 30,  512},
    {123456789LL, -300, 55,  300},
    {8675309LL,     64, 64,  -64},
};

/* Number of cp_provide_chunk generations one env's region requires (throughput bookkeeping). */
MC_HD static inline long brt_env_chunk_gens(const BrtEnv *env) {
    int cx0 = rt_floordiv16(env->x0),             cz0 = rt_floordiv16(env->z0);
    int cx1 = rt_floordiv16(env->x0 + BRT_NX - 1), cz1 = rt_floordiv16(env->z0 + BRT_NZ - 1);
    return (long)(cx1 - cx0 + 1) * (long)(cz1 - cz0 + 1);
}

/* Fill env `e`'s BRT_VOL-element slice of out_all with its dense block tensor. Caller
 * supplies this thread/env's own primer + scratch (off the device stack). */
MC_HD static inline void brt_fill_one(u16 *out_all, const BrtEnv *env, int e,
                                      ChunkPrimer *primer, CpScratch *sc,
                                      const McSinTable *st) {
    u16 *slice = out_all + (long)e * BRT_VOL;
    rt_fill(slice, (u64)env->seed, env->x0, env->y0, env->z0,
            BRT_NX, BRT_NY, BRT_NZ, primer, sc, st);
}

#endif /* MC_BATCH_REGION_TENSOR_H */
