#ifndef MAGMA_ITEM_DISPLAY_MANIFEST_H
#define MAGMA_ITEM_DISPLAY_MANIFEST_H
typedef struct { int id; const char *name; const char *display; } GmItemDisplay;
static const GmItemDisplay gm_item_displays[392] = {
    {0, "minecraft:air", "Air"},
    {1, "minecraft:stone", "Stone"},
    {2, "minecraft:grass", "Grass Block"},
    {3, "minecraft:dirt", "Dirt"},
    {4, "minecraft:cobblestone", "Cobblestone"},
    {5, "minecraft:planks", "Oak Wood Planks"},
    {6, "minecraft:sapling", "Oak Sapling"},
    {7, "minecraft:bedrock", "Bedrock"},
    {12, "minecraft:sand", "Sand"},
    {13, "minecraft:gravel", "Gravel"},
    {14, "minecraft:gold_ore", "Gold Ore"},
    {15, "minecraft:iron_ore", "Iron Ore"},
    {16, "minecraft:coal_ore", "Coal Ore"},
    {17, "minecraft:log", "Oak Wood"},
    {18, "minecraft:leaves", "Oak Leaves"},
    {19, "minecraft:sponge", "Sponge"},
    {20, "minecraft:glass", "Glass"},
    {21, "minecraft:lapis_ore", "Lapis Lazuli Ore"},
    {22, "minecraft:lapis_block", "Lapis Lazuli Block"},
    {23, "minecraft:dispenser", "Dispenser"},
    {24, "minecraft:sandstone", "Sandstone"},
    {25, "minecraft:noteblock", "Note Block"},
    {27, "minecraft:golden_rail", "Powered Rail"},
    {28, "minecraft:detector_rail", "Detector Rail"},
    {29, "minecraft:sticky_piston", "Sticky Piston"},
    {30, "minecraft:web", "Cobweb"},
    {31, "minecraft:tallgrass", "Shrub"},
    {32, "minecraft:deadbush", "Dead Bush"},
    {33, "minecraft:piston", "Piston"},
    {35, "minecraft:wool", "White Wool"},
    {37, "minecraft:yellow_flower", "Dandelion"},
    {38, "minecraft:red_flower", "Poppy"},
    {39, "minecraft:brown_mushroom", "Mushroom"},
    {40, "minecraft:red_mushroom", "Mushroom"},
    {41, "minecraft:gold_block", "Block of Gold"},
    {42, "minecraft:iron_block", "Block of Iron"},
    {44, "minecraft:stone_slab", "Stone Slab"},
    {45, "minecraft:brick_block", "Bricks"},
    {46, "minecraft:tnt", "TNT"},
    {47, "minecraft:bookshelf", "Bookshelf"},
    {48, "minecraft:mossy_cobblestone", "Moss Stone"},
    {49, "minecraft:obsidian", "Obsidian"},
    {50, "minecraft:torch", "Torch"},
    {52, "minecraft:mob_spawner", "Monster Spawner"},
    {53, "minecraft:oak_stairs", "Oak Wood Stairs"},
    {54, "minecraft:chest", "Chest"},
    {56, "minecraft:diamond_ore", "Diamond Ore"},
    {57, "minecraft:diamond_block", "Block of Diamond"},
    {58, "minecraft:crafting_table", "Crafting Table"},
    {60, "minecraft:farmland", "Farmland"},
    {61, "minecraft:furnace", "Furnace"},
    {65, "minecraft:ladder", "Ladder"},
    {66, "minecraft:rail", "Rail"},
    {67, "minecraft:stone_stairs", "Cobblestone Stairs"},
    {69, "minecraft:lever", "Lever"},
    {70, "minecraft:stone_pressure_plate", "Stone Pressure Plate"},
    {72, "minecraft:wooden_pressure_plate", "Wooden Pressure Plate"},
    {73, "minecraft:redstone_ore", "Redstone Ore"},
    {76, "minecraft:redstone_torch", "Redstone Torch"},
    {77, "minecraft:stone_button", "Button"},
    {78, "minecraft:snow_layer", "Snow"},
    {79, "minecraft:ice", "Ice"},
    {80, "minecraft:snow", "Snow"},
    {81, "minecraft:cactus", "Cactus"},
    {82, "minecraft:clay", "Clay"},
    {84, "minecraft:jukebox", "Jukebox"},
    {85, "minecraft:fence", "Oak Fence"},
    {86, "minecraft:pumpkin", "Pumpkin"},
    {87, "minecraft:netherrack", "Netherrack"},
    {88, "minecraft:soul_sand", "Soul Sand"},
    {89, "minecraft:glowstone", "Glowstone"},
    {91, "minecraft:lit_pumpkin", "Jack o'Lantern"},
    {95, "minecraft:stained_glass", "White Stained Glass"},
    {96, "minecraft:trapdoor", "Wooden Trapdoor"},
    {97, "minecraft:monster_egg", "Stone Monster Egg"},
    {98, "minecraft:stonebrick", "Stone Bricks"},
    {99, "minecraft:brown_mushroom_block", "Mushroom"},
    {100, "minecraft:red_mushroom_block", "Mushroom"},
    {101, "minecraft:iron_bars", "Iron Bars"},
    {102, "minecraft:glass_pane", "Glass Pane"},
    {103, "minecraft:melon_block", "Melon"},
    {106, "minecraft:vine", "Vines"},
    {107, "minecraft:fence_gate", "Oak Fence Gate"},
    {108, "minecraft:brick_stairs", "Brick Stairs"},
    {109, "minecraft:stone_brick_stairs", "Stone Brick Stairs"},
    {110, "minecraft:mycelium", "Mycelium"},
    {111, "minecraft:waterlily", "Lily Pad"},
    {112, "minecraft:nether_brick", "Nether Brick"},
    {113, "minecraft:nether_brick_fence", "Nether Brick Fence"},
    {114, "minecraft:nether_brick_stairs", "Nether Brick Stairs"},
    {116, "minecraft:enchanting_table", "Enchantment Table"},
    {120, "minecraft:end_portal_frame", "End Portal"},
    {121, "minecraft:end_stone", "End Stone"},
    {122, "minecraft:dragon_egg", "Dragon Egg"},
    {123, "minecraft:redstone_lamp", "Redstone Lamp"},
    {126, "minecraft:wooden_slab", "Oak Wood Slab"},
    {128, "minecraft:sandstone_stairs", "Sandstone Stairs"},
    {129, "minecraft:emerald_ore", "Emerald Ore"},
    {130, "minecraft:ender_chest", "Ender Chest"},
    {131, "minecraft:tripwire_hook", "Tripwire Hook"},
    {133, "minecraft:emerald_block", "Block of Emerald"},
    {134, "minecraft:spruce_stairs", "Spruce Wood Stairs"},
    {135, "minecraft:birch_stairs", "Birch Wood Stairs"},
    {136, "minecraft:jungle_stairs", "Jungle Wood Stairs"},
    {137, "minecraft:command_block", "Command Block"},
    {138, "minecraft:beacon", "Beacon"},
    {139, "minecraft:cobblestone_wall", "Cobblestone Wall"},
    {143, "minecraft:wooden_button", "Button"},
    {145, "minecraft:anvil", "Anvil"},
    {146, "minecraft:trapped_chest", "Trapped Chest"},
    {147, "minecraft:light_weighted_pressure_plate", "Weighted Pressure Plate (Light)"},
    {148, "minecraft:heavy_weighted_pressure_plate", "Weighted Pressure Plate (Heavy)"},
    {151, "minecraft:daylight_detector", "Daylight Sensor"},
    {152, "minecraft:redstone_block", "Block of Redstone"},
    {153, "minecraft:quartz_ore", "Nether Quartz Ore"},
    {154, "minecraft:hopper", "Hopper"},
    {155, "minecraft:quartz_block", "Block of Quartz"},
    {156, "minecraft:quartz_stairs", "Quartz Stairs"},
    {157, "minecraft:activator_rail", "Activator Rail"},
    {158, "minecraft:dropper", "Dropper"},
    {159, "minecraft:stained_hardened_clay", "White Hardened Clay"},
    {160, "minecraft:stained_glass_pane", "White Stained Glass Pane"},
    {161, "minecraft:leaves2", "Acacia Leaves"},
    {162, "minecraft:log2", "Acacia Wood"},
    {163, "minecraft:acacia_stairs", "Acacia Wood Stairs"},
    {164, "minecraft:dark_oak_stairs", "Dark Oak Wood Stairs"},
    {165, "minecraft:slime", "Slime Block"},
    {166, "minecraft:barrier", "Barrier"},
    {167, "minecraft:iron_trapdoor", "Iron Trapdoor"},
    {168, "minecraft:prismarine", "Prismarine"},
    {169, "minecraft:sea_lantern", "Sea Lantern"},
    {170, "minecraft:hay_block", "Hay Bale"},
    {171, "minecraft:carpet", "White Carpet"},
    {172, "minecraft:hardened_clay", "Hardened Clay"},
    {173, "minecraft:coal_block", "Block of Coal"},
    {174, "minecraft:packed_ice", "Packed Ice"},
    {175, "minecraft:double_plant", "Sunflower"},
    {179, "minecraft:red_sandstone", "Red Sandstone"},
    {180, "minecraft:red_sandstone_stairs", "Red Sandstone Stairs"},
    {182, "minecraft:stone_slab2", "Red Sandstone Slab"},
    {183, "minecraft:spruce_fence_gate", "Spruce Fence Gate"},
    {184, "minecraft:birch_fence_gate", "Birch Fence Gate"},
    {185, "minecraft:jungle_fence_gate", "Jungle Fence Gate"},
    {186, "minecraft:dark_oak_fence_gate", "Dark Oak Fence Gate"},
    {187, "minecraft:acacia_fence_gate", "Acacia Fence Gate"},
    {188, "minecraft:spruce_fence", "Spruce Fence"},
    {189, "minecraft:birch_fence", "Birch Fence"},
    {190, "minecraft:jungle_fence", "Jungle Fence"},
    {191, "minecraft:dark_oak_fence", "Dark Oak Fence"},
    {192, "minecraft:acacia_fence", "Acacia Fence"},
    {198, "minecraft:end_rod", "End Rod"},
    {199, "minecraft:chorus_plant", "Chorus Plant"},
    {200, "minecraft:chorus_flower", "Chorus Flower"},
    {201, "minecraft:purpur_block", "Purpur Block"},
    {202, "minecraft:purpur_pillar", "Purpur Pillar"},
    {203, "minecraft:purpur_stairs", "Purpur Stairs"},
    {205, "minecraft:purpur_slab", "Purpur Slab"},
    {206, "minecraft:end_bricks", "End Stone Bricks"},
    {208, "minecraft:grass_path", "Grass Path"},
    {210, "minecraft:repeating_command_block", "Repeating Command Block"},
    {211, "minecraft:chain_command_block", "Chain Command Block"},
    {213, "minecraft:magma", "Magma Block"},
    {214, "minecraft:nether_wart_block", "Nether Wart Block"},
    {215, "minecraft:red_nether_brick", "Red Nether Brick"},
    {216, "minecraft:bone_block", "Bone Block"},
    {217, "minecraft:structure_void", "Structure Void"},
    {218, "minecraft:observer", "Observer"},
    {219, "minecraft:white_shulker_box", "White Shulker Box"},
    {220, "minecraft:orange_shulker_box", "Orange Shulker Box"},
    {221, "minecraft:magenta_shulker_box", "Magenta Shulker Box"},
    {222, "minecraft:light_blue_shulker_box", "Light Blue Shulker Box"},
    {223, "minecraft:yellow_shulker_box", "Yellow Shulker Box"},
    {224, "minecraft:lime_shulker_box", "Lime Shulker Box"},
    {225, "minecraft:pink_shulker_box", "Pink Shulker Box"},
    {226, "minecraft:gray_shulker_box", "Gray Shulker Box"},
    {227, "minecraft:silver_shulker_box", "Light Gray Shulker Box"},
    {228, "minecraft:cyan_shulker_box", "Cyan Shulker Box"},
    {229, "minecraft:purple_shulker_box", "Purple Shulker Box"},
    {230, "minecraft:blue_shulker_box", "Blue Shulker Box"},
    {231, "minecraft:brown_shulker_box", "Brown Shulker Box"},
    {232, "minecraft:green_shulker_box", "Green Shulker Box"},
    {233, "minecraft:red_shulker_box", "Red Shulker Box"},
    {234, "minecraft:black_shulker_box", "Black Shulker Box"},
    {255, "minecraft:structure_block", "Structure Block"},
    {256, "minecraft:iron_shovel", "Iron Shovel"},
    {257, "minecraft:iron_pickaxe", "Iron Pickaxe"},
    {258, "minecraft:iron_axe", "Iron Axe"},
    {259, "minecraft:flint_and_steel", "Flint and Steel"},
    {260, "minecraft:apple", "Apple"},
    {261, "minecraft:bow", "Bow"},
    {262, "minecraft:arrow", "Arrow"},
    {263, "minecraft:coal", "Coal"},
    {264, "minecraft:diamond", "Diamond"},
    {265, "minecraft:iron_ingot", "Iron Ingot"},
    {266, "minecraft:gold_ingot", "Gold Ingot"},
    {267, "minecraft:iron_sword", "Iron Sword"},
    {268, "minecraft:wooden_sword", "Wooden Sword"},
    {269, "minecraft:wooden_shovel", "Wooden Shovel"},
    {270, "minecraft:wooden_pickaxe", "Wooden Pickaxe"},
    {271, "minecraft:wooden_axe", "Wooden Axe"},
    {272, "minecraft:stone_sword", "Stone Sword"},
    {273, "minecraft:stone_shovel", "Stone Shovel"},
    {274, "minecraft:stone_pickaxe", "Stone Pickaxe"},
    {275, "minecraft:stone_axe", "Stone Axe"},
    {276, "minecraft:diamond_sword", "Diamond Sword"},
    {277, "minecraft:diamond_shovel", "Diamond Shovel"},
    {278, "minecraft:diamond_pickaxe", "Diamond Pickaxe"},
    {279, "minecraft:diamond_axe", "Diamond Axe"},
    {280, "minecraft:stick", "Stick"},
    {281, "minecraft:bowl", "Bowl"},
    {282, "minecraft:mushroom_stew", "Mushroom Stew"},
    {283, "minecraft:golden_sword", "Golden Sword"},
    {284, "minecraft:golden_shovel", "Golden Shovel"},
    {285, "minecraft:golden_pickaxe", "Golden Pickaxe"},
    {286, "minecraft:golden_axe", "Golden Axe"},
    {287, "minecraft:string", "String"},
    {288, "minecraft:feather", "Feather"},
    {289, "minecraft:gunpowder", "Gunpowder"},
    {290, "minecraft:wooden_hoe", "Wooden Hoe"},
    {291, "minecraft:stone_hoe", "Stone Hoe"},
    {292, "minecraft:iron_hoe", "Iron Hoe"},
    {293, "minecraft:diamond_hoe", "Diamond Hoe"},
    {294, "minecraft:golden_hoe", "Golden Hoe"},
    {295, "minecraft:wheat_seeds", "Seeds"},
    {296, "minecraft:wheat", "Wheat"},
    {297, "minecraft:bread", "Bread"},
    {298, "minecraft:leather_helmet", "Leather Cap"},
    {299, "minecraft:leather_chestplate", "Leather Tunic"},
    {300, "minecraft:leather_leggings", "Leather Pants"},
    {301, "minecraft:leather_boots", "Leather Boots"},
    {302, "minecraft:chainmail_helmet", "Chain Helmet"},
    {303, "minecraft:chainmail_chestplate", "Chain Chestplate"},
    {304, "minecraft:chainmail_leggings", "Chain Leggings"},
    {305, "minecraft:chainmail_boots", "Chain Boots"},
    {306, "minecraft:iron_helmet", "Iron Helmet"},
    {307, "minecraft:iron_chestplate", "Iron Chestplate"},
    {308, "minecraft:iron_leggings", "Iron Leggings"},
    {309, "minecraft:iron_boots", "Iron Boots"},
    {310, "minecraft:diamond_helmet", "Diamond Helmet"},
    {311, "minecraft:diamond_chestplate", "Diamond Chestplate"},
    {312, "minecraft:diamond_leggings", "Diamond Leggings"},
    {313, "minecraft:diamond_boots", "Diamond Boots"},
    {314, "minecraft:golden_helmet", "Golden Helmet"},
    {315, "minecraft:golden_chestplate", "Golden Chestplate"},
    {316, "minecraft:golden_leggings", "Golden Leggings"},
    {317, "minecraft:golden_boots", "Golden Boots"},
    {318, "minecraft:flint", "Flint"},
    {319, "minecraft:porkchop", "Raw Porkchop"},
    {320, "minecraft:cooked_porkchop", "Cooked Porkchop"},
    {321, "minecraft:painting", "Painting"},
    {322, "minecraft:golden_apple", "Golden Apple"},
    {323, "minecraft:sign", "Sign"},
    {324, "minecraft:wooden_door", "Oak Door"},
    {325, "minecraft:bucket", "Bucket"},
    {326, "minecraft:water_bucket", "Water Bucket"},
    {327, "minecraft:lava_bucket", "Lava Bucket"},
    {328, "minecraft:minecart", "Minecart"},
    {329, "minecraft:saddle", "Saddle"},
    {330, "minecraft:iron_door", "Iron Door"},
    {331, "minecraft:redstone", "Redstone"},
    {332, "minecraft:snowball", "Snowball"},
    {333, "minecraft:boat", "Oak Boat"},
    {334, "minecraft:leather", "Leather"},
    {335, "minecraft:milk_bucket", "Milk"},
    {336, "minecraft:brick", "Brick"},
    {337, "minecraft:clay_ball", "Clay"},
    {338, "minecraft:reeds", "Sugar Canes"},
    {339, "minecraft:paper", "Paper"},
    {340, "minecraft:book", "Book"},
    {341, "minecraft:slime_ball", "Slimeball"},
    {342, "minecraft:chest_minecart", "Minecart with Chest"},
    {343, "minecraft:furnace_minecart", "Minecart with Furnace"},
    {344, "minecraft:egg", "Egg"},
    {345, "minecraft:compass", "Compass"},
    {346, "minecraft:fishing_rod", "Fishing Rod"},
    {347, "minecraft:clock", "Clock"},
    {348, "minecraft:glowstone_dust", "Glowstone Dust"},
    {349, "minecraft:fish", "Raw Fish"},
    {350, "minecraft:cooked_fish", "Cooked Fish"},
    {351, "minecraft:dye", "Ink Sac"},
    {352, "minecraft:bone", "Bone"},
    {353, "minecraft:sugar", "Sugar"},
    {354, "minecraft:cake", "Cake"},
    {355, "minecraft:bed", "Bed"},
    {356, "minecraft:repeater", "Redstone Repeater"},
    {357, "minecraft:cookie", "Cookie"},
    {358, "minecraft:filled_map", "Map"},
    {359, "minecraft:shears", "Shears"},
    {360, "minecraft:melon", "Melon"},
    {361, "minecraft:pumpkin_seeds", "Pumpkin Seeds"},
    {362, "minecraft:melon_seeds", "Melon Seeds"},
    {363, "minecraft:beef", "Raw Beef"},
    {364, "minecraft:cooked_beef", "Steak"},
    {365, "minecraft:chicken", "Raw Chicken"},
    {366, "minecraft:cooked_chicken", "Cooked Chicken"},
    {367, "minecraft:rotten_flesh", "Rotten Flesh"},
    {368, "minecraft:ender_pearl", "Ender Pearl"},
    {369, "minecraft:blaze_rod", "Blaze Rod"},
    {370, "minecraft:ghast_tear", "Ghast Tear"},
    {371, "minecraft:gold_nugget", "Gold Nugget"},
    {372, "minecraft:nether_wart", "Nether Wart"},
    {373, "minecraft:potion", "Uncraftable Potion"},
    {374, "minecraft:glass_bottle", "Glass Bottle"},
    {375, "minecraft:spider_eye", "Spider Eye"},
    {376, "minecraft:fermented_spider_eye", "Fermented Spider Eye"},
    {377, "minecraft:blaze_powder", "Blaze Powder"},
    {378, "minecraft:magma_cream", "Magma Cream"},
    {379, "minecraft:brewing_stand", "Brewing Stand"},
    {380, "minecraft:cauldron", "Cauldron"},
    {381, "minecraft:ender_eye", "Eye of Ender"},
    {382, "minecraft:speckled_melon", "Glistering Melon"},
    {383, "minecraft:spawn_egg", "Spawn"},
    {384, "minecraft:experience_bottle", "Bottle o' Enchanting"},
    {385, "minecraft:fire_charge", "Fire Charge"},
    {386, "minecraft:writable_book", "Book and Quill"},
    {387, "minecraft:written_book", "Written Book"},
    {388, "minecraft:emerald", "Emerald"},
    {389, "minecraft:item_frame", "Item Frame"},
    {390, "minecraft:flower_pot", "Flower Pot"},
    {391, "minecraft:carrot", "Carrot"},
    {392, "minecraft:potato", "Potato"},
    {393, "minecraft:baked_potato", "Baked Potato"},
    {394, "minecraft:poisonous_potato", "Poisonous Potato"},
    {395, "minecraft:map", "Empty Map"},
    {396, "minecraft:golden_carrot", "Golden Carrot"},
    {397, "minecraft:skull", "Skeleton Skull"},
    {398, "minecraft:carrot_on_a_stick", "Carrot on a Stick"},
    {399, "minecraft:nether_star", "Nether Star"},
    {400, "minecraft:pumpkin_pie", "Pumpkin Pie"},
    {401, "minecraft:fireworks", "Firework Rocket"},
    {402, "minecraft:firework_charge", "Firework Star"},
    {403, "minecraft:enchanted_book", "Enchanted Book"},
    {404, "minecraft:comparator", "Redstone Comparator"},
    {405, "minecraft:netherbrick", "Nether Brick"},
    {406, "minecraft:quartz", "Nether Quartz"},
    {407, "minecraft:tnt_minecart", "Minecart with TNT"},
    {408, "minecraft:hopper_minecart", "Minecart with Hopper"},
    {409, "minecraft:prismarine_shard", "Prismarine Shard"},
    {410, "minecraft:prismarine_crystals", "Prismarine Crystals"},
    {411, "minecraft:rabbit", "Raw Rabbit"},
    {412, "minecraft:cooked_rabbit", "Cooked Rabbit"},
    {413, "minecraft:rabbit_stew", "Rabbit Stew"},
    {414, "minecraft:rabbit_foot", "Rabbit's Foot"},
    {415, "minecraft:rabbit_hide", "Rabbit Hide"},
    {416, "minecraft:armor_stand", "Armor Stand"},
    {417, "minecraft:iron_horse_armor", "Iron Horse Armor"},
    {418, "minecraft:golden_horse_armor", "Gold Horse Armor"},
    {419, "minecraft:diamond_horse_armor", "Diamond Horse Armor"},
    {420, "minecraft:lead", "Lead"},
    {421, "minecraft:name_tag", "Name Tag"},
    {422, "minecraft:command_block_minecart", "Minecart with Command Block"},
    {423, "minecraft:mutton", "Raw Mutton"},
    {424, "minecraft:cooked_mutton", "Cooked Mutton"},
    {425, "minecraft:banner", "Black Banner"},
    {426, "minecraft:end_crystal", "End Crystal"},
    {427, "minecraft:spruce_door", "Spruce Door"},
    {428, "minecraft:birch_door", "Birch Door"},
    {429, "minecraft:jungle_door", "Jungle Door"},
    {430, "minecraft:acacia_door", "Acacia Door"},
    {431, "minecraft:dark_oak_door", "Dark Oak Door"},
    {432, "minecraft:chorus_fruit", "Chorus Fruit"},
    {433, "minecraft:chorus_fruit_popped", "Popped Chorus Fruit"},
    {434, "minecraft:beetroot", "Beetroot"},
    {435, "minecraft:beetroot_seeds", "Beetroot Seeds"},
    {436, "minecraft:beetroot_soup", "Beetroot Soup"},
    {437, "minecraft:dragon_breath", "Dragon's Breath"},
    {438, "minecraft:splash_potion", "Splash Uncraftable Potion"},
    {439, "minecraft:spectral_arrow", "Spectral Arrow"},
    {440, "minecraft:tipped_arrow", "Uncraftable Tipped Arrow"},
    {441, "minecraft:lingering_potion", "Lingering Uncraftable Potion"},
    {442, "minecraft:shield", "Shield"},
    {443, "minecraft:elytra", "Elytra"},
    {444, "minecraft:spruce_boat", "Spruce Boat"},
    {445, "minecraft:birch_boat", "Birch Boat"},
    {446, "minecraft:jungle_boat", "Jungle Boat"},
    {447, "minecraft:acacia_boat", "Acacia Boat"},
    {448, "minecraft:dark_oak_boat", "Dark Oak Boat"},
    {449, "minecraft:totem_of_undying", "Totem of Undying"},
    {450, "minecraft:shulker_shell", "Shulker Shell"},
    {452, "minecraft:iron_nugget", "Iron Nugget"},
    {2256, "minecraft:record_13", "Music Disc"},
    {2257, "minecraft:record_cat", "Music Disc"},
    {2258, "minecraft:record_blocks", "Music Disc"},
    {2259, "minecraft:record_chirp", "Music Disc"},
    {2260, "minecraft:record_far", "Music Disc"},
    {2261, "minecraft:record_mall", "Music Disc"},
    {2262, "minecraft:record_mellohi", "Music Disc"},
    {2263, "minecraft:record_stal", "Music Disc"},
    {2264, "minecraft:record_strad", "Music Disc"},
    {2265, "minecraft:record_ward", "Music Disc"},
    {2266, "minecraft:record_11", "Music Disc"},
    {2267, "minecraft:record_wait", "Music Disc"},
};
#endif
