#!/usr/bin/env perl
# oracle.patch: every edit to the decompiled, determinized vanilla tree,
# written so that it carries as little of the vanilla text as it can.
#
#   perl oraclepatch.pl apply BASE PATCH       rewrite the tree BASE in place
#   perl oraclepatch.pl make BASE NEW > PATCH  the patch that turns BASE into NEW
#   perl oraclepatch.pl verbatim PATCH TREE    the patch's literal lines that also
#                                              occur verbatim in a file of TREE
#
# The format, one op a line ('#' lines before the first op are comments):
#   D path       delete the file
#   M path       rebuild the file from the ops that follow, out of its old lines
#   N path       a new file, from the ops that follow
#   = a n        copy the old file's lines a .. a+n-1 (1-based)
#   > a n d      the same, each non-blank line shifted right d spaces (left if d < 0)
#   < path a n d the same from another file of the old tree
#   + n          the next n lines of the patch, as they are
#   \            the file ends without a newline
# A deletion names no deleted text, and a kept, moved or re-indented line is
# a line range, so the only vanilla text a patch can hold is in its + lines:
# a vanilla line with an edit in it (oraclepatch.pl verbatim counts the rest,
# lines of ours that happen to equal a vanilla line, which make never leaves).
use strict;
use warnings;
use File::Find;
use File::Path qw(make_path);
use File::Basename qw(dirname);

sub slurp {
  my ($f) = @_;
  open my $h, '<:raw', $f or die "$f: $!";
  local $/; my $s = <$h>; close $h;
  my $eol = $s eq '' || substr($s, -1) eq "\n";
  my @l = split /\n/, $s, -1;
  pop @l if $eol && @l;
  return (\@l, $eol);
}

sub files {
  my ($root) = @_;
  my @f;
  find({ no_chdir => 1, wanted => sub { push @f, substr($_, length($root) + 1) if -f $_ } }, $root);
  return sort @f;
}

my $cmd = shift // '';
if ($cmd eq 'apply') {
  my ($base, $patch) = @ARGV;
  open my $p, '<:raw', $patch or die "$patch: $!";
  my @p = map { chomp; $_ } <$p>;
  close $p;
  my $i = 0;
  $i++ while $i < @p && $p[$i] =~ /^#/;
  # every copy reads the old tree: build every file in memory, then write
  my (%old, @del, @put);
  my $get = sub { my $f = shift; $old{$f} //= (slurp("$base/$f"))[0] };
  while ($i < @p) {
    my $op = $p[$i++];
    if ($op =~ /^D (.+)$/) { push @del, $1; next }
    $op =~ /^([MN]) (.+)$/ or die "$patch:$i: expected D, M or N: $op";
    my ($kind, $path) = ($1, $2);
    die "N $path: exists" if $kind eq 'N' && -e "$base/$path";
    my (@out, $eol);
    $eol = 1;
    while ($i < @p && $p[$i] !~ /^[DMN] /) {
      my $o = $p[$i++];
      my ($src, $a, $n, $d);
      if ($o =~ /^= (\d+) (\d+)$/) { ($src, $a, $n, $d) = ($path, $1, $2, 0) }
      elsif ($o =~ /^> (\d+) (\d+) (-?\d+)$/) { ($src, $a, $n, $d) = ($path, $1, $2, $3) }
      elsif ($o =~ /^< (\S+) (\d+) (\d+) (-?\d+)$/) { ($src, $a, $n, $d) = ($1, $2, $3, $4) }
      elsif ($o =~ /^\+ (\d+)$/) {
        die "$patch: + $1 past the end" if $i + $1 > @p;
        push @out, @p[$i .. $i + $1 - 1]; $i += $1; next;
      } elsif ($o eq '\\') { $eol = 0; next }
      else { die "$patch:$i: bad op: $o" }
      die "$path: copy from $src in a new file" if $kind eq 'N' && $src eq $path;
      my $L = $get->($src);
      die "$path: $o: past the end of $src (" . scalar(@$L) . ")" if $a < 1 || $a + $n - 1 > @$L;
      for my $l (@$L[$a - 1 .. $a + $n - 2]) {
        if ($l eq '' || !$d) { push @out, $l }
        elsif ($d > 0) { push @out, (' ' x $d) . $l }
        else { $l =~ /^ {${\ -$d}}/ or die "$path: $o: cannot unindent: $l"; push @out, substr($l, -$d) }
      }
    }
    push @put, [$path, \@out, $eol];
  }
  for (@del) { unlink "$base/$_" or die "D $_: $!" }
  for (@put) {
    my ($path, $out, $eol) = @$_;
    make_path(dirname("$base/$path"));
    open my $h, '>:raw', "$base/$path" or die "$path: $!";
    print $h join("\n", @$out), (@$out && $eol ? "\n" : '');
    close $h;
  }
  # no directory a deletion emptied
  finddepth({ no_chdir => 1, wanted => sub { rmdir $_ if -d $_ && $_ ne $base } }, $base);
  print STDERR "oraclepatch: ", scalar(@del), " deleted, ", scalar(@put), " written\n";
} elsif ($cmd eq 'make') {
  my ($base, $new) = @ARGV;
  my %b = map { $_ => 1 } files($base);
  my %n = map { $_ => 1 } files($new);
  # the old tree, and every old line by its text without leading spaces
  our (%base, %all);
  for my $f (sort keys %b) {
    $base{$f} = (slurp("$base/$f"))[0];
    my $L = $base{$f};
    push @{ $all{ strip($L->[$_]) } }, [$f, $_] for 0 .. $#$L;
  }
  print "# oracle.patch: generated by oracle/decomp/mkpatch.sh; format in oraclepatch.pl\n";
  for my $f (sort grep { !$n{$_} } keys %b) { print "D $f\n" }
  for my $f (sort keys %n) {
    my ($nl, $neol) = slurp("$new/$f");
    my ($ol, $oeol) = ([], 1);
    if ($b{$f}) {
      ($ol, $oeol) = slurp("$base/$f");
      next if $neol == $oeol && join("\n", @$ol) eq join("\n", @$nl) && @$ol == @$nl;
    }
    print(($b{$f} ? 'M' : 'N'), " $f\n");
    # every new line is a copy of old lines where it can be: diff's longest
    # common subsequence first (a few edits in place cost few copy ops), then
    # the longest run of this file's old lines from any start, equal or
    # shifted in indentation by a constant, then the same over every other
    # file of the old tree; else a literal
    my $si = idx($f, $ol);
    my @keep = @$ol ? @{ diffmap($ol, $nl) } : ((-1) x @$nl);    # new index -> old index
    my @ops;
    my $i = 0;
    while ($i < @$nl) {
      my ($src, $j, $k, $dd) = ($f, -1, 0, 0);
      if ($keep[$i] >= 0) {
        $j = $keep[$i]; $k = 1;
        $k++ while $i + $k < @$nl && $keep[$i + $k] == $j + $k;
      } else {
        for my $pass (0, 1) {
          my @c = $pass ? @{ $all{ strip($nl->[$i]) } // [] } : map { [$f, $_] } @{ $si->{ strip($nl->[$i]) } // [] };
          for my $c (@c) {
            my ($cf, $s) = @$c;
            next if $pass && $cf eq $f;
            my $L = $pass ? $base{$cf} : $ol;
            my $d = indent($nl->[$i]) - indent($L->[$s]);
            next unless shift_ok($L->[$s], $d, $nl->[$i]);
            my $m = 1;
            $m++ while $i + $m < @$nl && $s + $m < @$L && $keep[$i + $m] < 0 && shift_ok($L->[$s + $m], $d, $nl->[$i + $m]);
            ($src, $j, $k, $dd) = ($cf, $s, $m, $d) if $m > $k || ($m == $k && $d == 0 && $dd != 0);
          }
          last if $k;
        }
      }
      if ($k) {
        my $o = $ops[-1];
        if ($o && $o->[0] eq 'c' && $o->[1] eq $src && $o->[4] == $dd && $o->[2] + $o->[3] == $j + 1) { $o->[3] += $k }
        else { push @ops, ['c', $src, $j + 1, $k, $dd] }
        $i += $k;
      } else {
        if (@ops && $ops[-1][0] eq '+') { push @{ $ops[-1][1] }, $nl->[$i] }
        else { push @ops, ['+', [$nl->[$i]]] }
        $i++;
      }
    }
    for my $o (@ops) {
      if ($o->[0] eq '+') { print '+ ', scalar(@{ $o->[1] }), "\n", map { "$_\n" } @{ $o->[1] } }
      elsif ($o->[1] ne $f) { print "< $o->[1] $o->[2] $o->[3] $o->[4]\n" }
      elsif ($o->[4]) { print "> $o->[2] $o->[3] $o->[4]\n" }
      else { print "= $o->[2] $o->[3]\n" }
    }
    print "\\\n" unless $neol;
  }
} elsif ($cmd eq 'verbatim') {
  my ($patch, $tree) = @ARGV;
  my %v;
  for my $f (files($tree)) { my ($l) = slurp("$tree/$f"); $v{$_} = 1 for @$l }
  open my $p, '<:raw', $patch or die "$patch: $!";
  my @p = map { chomp; $_ } <$p>;
  my ($i, $file, $lit, $hit) = (0, '', 0, 0);
  while ($i < @p) {
    my $o = $p[$i++];
    if ($o =~ /^[DMN] (.+)$/) { $file = $1; next }
    next unless $o =~ /^\+ (\d+)$/;
    for my $l (@p[$i .. $i + $1 - 1]) {
      $lit++;
      if ($v{$l}) { $hit++; print "$file\t$l\n" }
    }
    $i += $1;
  }
  print STDERR "oraclepatch: $lit literal lines, $hit verbatim in $tree\n";
} else {
  die "usage: oraclepatch.pl apply BASE PATCH | make BASE NEW | verbatim PATCH TREE\n";
}

# diff's longest common subsequence as a map: new index -> old index or -1
sub diffmap {
  my ($ol, $nl) = @_;
  my $tmp = $ENV{TMPDIR} // '/tmp';
  my ($a, $b) = ("$tmp/oraclepatch.$$.a", "$tmp/oraclepatch.$$.b");
  for ([$a, $ol], [$b, $nl]) {
    open my $h, '>:raw', $_->[0] or die; print $h map { "$_\n" } @{ $_->[1] }; close $h;
  }
  my @m = (-1) x @$nl;
  open my $d, '-|', 'diff', '-n', $a, $b or die "diff: $!";
  my @d = map { chomp; $_ } <$d>;
  close $d;
  unlink $a, $b;
  # walk the edit script: old lines not deleted map in order to new lines not added
  my (%del, %add);    # old line deleted; new lines added after old line L
  my $i = 0;
  while ($i < @d) {
    my ($t, $l, $c) = $d[$i++] =~ /^([ad])(\d+) (\d+)$/ or die "diff -n: $d[$i-1]";
    if ($t eq 'd') { $del{$_} = 1 for $l .. $l + $c - 1 }
    else { $add{$l} += $c; $i += $c }
  }
  my $nj = 0;
  $nj += $add{0} // 0;
  for my $oj (1 .. @$ol) {
    $m[$nj++] = $oj - 1 unless $del{$oj};
    $nj += $add{$oj} // 0;
  }
  die "diffmap: $nj != " . scalar(@$nl) unless $nj == @$nl;
  return \@m;
}

sub strip { my $s = shift; $s =~ s/^ +//; $s }
sub indent { $_[0] =~ /^( *)/; length $1 }
# a file's lines by their text without leading spaces
sub idx { my ($f, $L) = @_; my %i; push @{ $i{ strip($L->[$_]) } }, $_ for 0 .. $#$L; \%i }
# OLD shifted right by D spaces (left when negative) is NEW; blank stays blank
sub shift_ok {
  my ($o, $d, $n) = @_;
  return $n eq '' if $o eq '';
  return $o eq $n unless $d;
  return $n eq (' ' x $d) . $o if $d > 0;
  return substr($o, 0, -$d) eq ' ' x -$d && substr($o, -$d) eq $n;
}
