package netherite.oracle;

import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.List;
import net.minecraft.block.Block;
import net.minecraft.world.biome.BiomeGenBase;
import net.minecraft.world.biome.BiomeGenMesa;
import net.minecraft.world.biome.BiomeGenMutated;

/**
 * Writes the biome registry for the native port, read through the oracle's own
 * methods so no value is transcribed by hand: a C header of the structs and the
 * extern declaration, and the one C file that defines the table. Floats are
 * exact (hex literals). Run with `make -C oracle biomes-h`.
 */
public final class BiomeTable
{
    private BiomeTable() {}

    static final String[] SURF = {"SURF_GENERIC", "SURF_HILLS", "SURF_TAIGA", "SURF_SAVANNA_M", "SURF_SWAMP", "SURF_MESA", "SURF_MUTATED"};

    /** {kind, p1, p2}: the surface routine this object runs and its type fields. */
    static int[] surface(BiomeGenBase b) throws Exception
    {
        Class<?> c = b.getClass();
        if (c.getName().endsWith("BiomeGenSavanna$Mutated")) return new int[] {3, 0, 0};
        if (b instanceof BiomeGenMutated) return new int[] {6, 0, 0};
        if (c == net.minecraft.world.biome.BiomeGenHills.class) return new int[] {1, intField(c, b, "field_150638_aH"), 0};
        if (c == net.minecraft.world.biome.BiomeGenTaiga.class) return new int[] {2, intField(c, b, "field_150644_aH"), 0};
        if (c == net.minecraft.world.biome.BiomeGenSwamp.class) return new int[] {4, 0, 0};
        if (c == BiomeGenMesa.class) return new int[] {5, boolField(c, b, "field_150626_aH"), boolField(c, b, "field_150620_aI")};
        return new int[] {0, 0, 0};
    }

    static int intField(Class<?> c, Object o, String n) throws Exception
    {
        Field f = c.getDeclaredField(n);
        f.setAccessible(true);
        return f.getInt(o);
    }

    static int boolField(Class<?> c, Object o, String n) throws Exception
    {
        Field f = c.getDeclaredField(n);
        f.setAccessible(true);
        return f.getBoolean(o) ? 1 : 0;
    }

    public static void main(String[] args) throws Exception
    {
        net.minecraft.init.Bootstrap.func_151354_b(); // registers blocks and items, which biome statics reference
        write(new File(args[0]), new File(args[1]));
        System.out.println("wrote " + args[0] + " " + args[1]);
    }

    static void write(File out, File defs) throws Exception
    {
        BiomeGenBase[] list = BiomeGenBase.getBiomeGenArray();
        List<String> classes = new ArrayList<String>();
        for (BiomeGenBase b : list)
        {
            if (b == null) continue;
            String c = b.func_150562_l().getSimpleName();
            if (!classes.contains(c)) classes.add(c);
        }
        Field base = BiomeGenMutated.class.getDeclaredField("field_150611_aD");
        base.setAccessible(true);

        out.getParentFile().mkdirs();
        PrintWriter w = new PrintWriter(new OutputStreamWriter(new FileOutputStream(out), "UTF-8"));
        PrintWriter d = new PrintWriter(new OutputStreamWriter(new FileOutputStream(defs), "UTF-8"));
        d.println("/* The biome registry's tables, declared in " + out.getName() + ", defined here once.");
        d.println(" * Generated by netherite.oracle.BiomeTable from the oracle");
        d.println(" * (make -C oracle biomes-h); do not edit by hand. */");
        d.println("#include \"" + out.getName() + "\"");
        d.println();
        w.println("/* Minecraft 1.7.10 biome registry. Generated by netherite.oracle.BiomeTable");
        w.println(" * from the oracle (make -C oracle biomes-h); do not edit by hand. */");
        w.println("#ifndef NETHERITE_BIOMES_H");
        w.println("#define NETHERITE_BIOMES_H");
        w.println();
        w.println("/* getBiomeClass(): layers compare biomes by it; a mutation reports its base's class */");
        w.println("enum biome_class {");
        for (int i = 0; i < classes.size(); ++i) w.println("    CLS_" + classes.get(i).replace("BiomeGen", "").toUpperCase() + " = " + (i + 1) + ",");
        w.println("};");
        w.println();
        w.println("enum temp_category { TEMP_OCEAN, TEMP_COLD, TEMP_MEDIUM, TEMP_WARM };");
        w.println();
        w.println("/* which func_150573_a (surface) the object runs; MUTATED delegates to base */");
        w.println("enum surface_kind { SURF_GENERIC, SURF_HILLS, SURF_TAIGA, SURF_SAVANNA_M, SURF_SWAMP, SURF_MESA, SURF_MUTATED };");
        w.println();
        w.println("struct biome_def {");
        w.println("    const char *name;");
        w.println("    unsigned char exists, cls, temp_cat, snow, mesa, lightning;  /* lightning: canSpawnLightningBolt() */");
        w.println("    short base;              /* mutation: the biome it mutates, else -1 */");
        w.println("    short object_id;         /* biomeID of the object in this slot: 161 aliases 160 in 1.7.10 */");
        w.println("    float root, variation;   /* minHeight, maxHeight */");
        w.println("    float temperature, rainfall;");
        w.println("    unsigned short top, top_meta, filler;  /* filler is always placed with meta 0 */");
        w.println("    unsigned char surface;   /* enum surface_kind */");
        w.println("    unsigned char p1, p2;    /* hills: type; taiga: type; mesa: bryce, forest */");
        w.println("};");
        w.println();
        w.println("extern const struct biome_def BIOMES[256];");
        w.println();
        d.println("const struct biome_def BIOMES[256] = {");
        for (int id = 0; id < list.length; ++id)
        {
            BiomeGenBase b = list[id];
            if (b == null) continue;
            String cls = "CLS_" + b.func_150562_l().getSimpleName().replace("BiomeGen", "").toUpperCase();
            String temp = "TEMP_" + b.func_150561_m().name();
            int baseId = b instanceof BiomeGenMutated ? ((BiomeGenBase)base.get(b)).biomeID : -1;
            int[] sk = surface(b);
            d.println(String.format("    [%d] = {\"%s\", 1, %s, %s, %d, %d, %d, %d, %d, %sf, %sf, %sf, %sf, %d, %d, %d, %s, %d, %d},",
                id, b.biomeName, cls, temp, b.func_150559_j() ? 1 : 0, b instanceof BiomeGenMesa ? 1 : 0,
                b.canSpawnLightningBolt() ? 1 : 0, baseId, b.biomeID,
                Float.toHexString(b.minHeight), Float.toHexString(b.maxHeight),
                Float.toHexString(b.temperature), Float.toHexString(b.rainfall),
                Block.getIdFromBlock(b.topBlock), b.field_150604_aj, Block.getIdFromBlock(b.fillerBlock),
                SURF[sk[0]], sk[1], sk[2]));
        }
        d.println("};");
        w.println("#endif");
        w.close();
        d.close();
    }
}
