package netherite.oracle;

import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.util.ArrayList;
import java.util.List;
import net.minecraft.block.Block;
import net.minecraft.block.ITileEntityProvider;
import net.minecraft.block.material.Material;

/**
 * Writes the block registry's static properties for the native port, read
 * through the oracle's own methods so no value is transcribed by hand: a C
 * header of the structs and extern declarations, and the one C file that
 * defines the tables (every unit that includes the header shares them).
 * Floats are exact (hex literals). Run with `make -C oracle blocks-h`.
 */
public final class BlockTable
{
    private BlockTable() {}

    /** the ids the native port's 12-bit block array can hold */
    static final int IDS = 4096;

    /** Every distinct Material object a registered block uses, in block-id order. */
    static List<Material> materials()
    {
        List<Material> out = new ArrayList<Material>();
        for (int id = 0; id < IDS; ++id)
        {
            if (!Block.blockRegistry.containsID(id)) continue;
            Material m = Block.getBlockById(id).getMaterial();
            if (!out.contains(m)) out.add(m);
        }
        return out;
    }

    /** The field name Material.java declares for this object. */
    static String materialName(Material m) throws Exception
    {
        for (Field f : Material.class.getDeclaredFields())
        {
            if (!Modifier.isStatic(f.getModifiers()) || !Material.class.isAssignableFrom(f.getType())) continue;
            f.setAccessible(true);
            if (f.get(null) == m) return f.getName();
        }
        throw new IllegalStateException("Material " + m + " has no field in Material.java");
    }

    static float floatField(Class<?> c, Object o, String n) throws Exception
    {
        Field f = c.getDeclaredField(n);
        f.setAccessible(true);
        return f.getFloat(o);
    }

    static double doubleField(Class<?> c, Object o, String n) throws Exception
    {
        Field f = c.getDeclaredField(n);
        f.setAccessible(true);
        return f.getDouble(o);
    }

    public static void main(String[] args) throws Exception
    {
        net.minecraft.init.Bootstrap.func_151354_b(); // registers blocks and items
        write(new File(args[0]), new File(args[1]));
        System.out.println("wrote " + args[0] + " " + args[1]);
    }

    static void write(File out, File defs) throws Exception
    {
        List<Material> mats = materials();

        out.getParentFile().mkdirs();
        PrintWriter w = new PrintWriter(new OutputStreamWriter(new FileOutputStream(out), "UTF-8"));
        PrintWriter d = new PrintWriter(new OutputStreamWriter(new FileOutputStream(defs), "UTF-8"));
        d.println("/* The block registry's tables, declared in " + out.getName() + ", defined here once.");
        d.println(" * Generated by netherite.oracle.BlockTable from the oracle");
        d.println(" * (make -C oracle blocks-h); do not edit by hand. */");
        d.println("#include \"" + out.getName() + "\"");
        d.println();
        w.println("/* Minecraft 1.7.10 block registry: the static properties world population,");
        w.println(" * block interaction and player physics read. Generated by");
        w.println(" * netherite.oracle.BlockTable from the oracle (make -C oracle blocks-h);");
        w.println(" * do not edit by hand. */");
        w.println("#ifndef NETHERITE_BLOCKS_H");
        w.println("#define NETHERITE_BLOCKS_H");
        w.println();
        w.println("/* one entry per distinct Material object a registered block uses */");
        w.println("struct material_def {");
        w.println("    const char *name;");
        w.println("    unsigned char is_liquid, is_solid, blocks_movement, can_burn, replaceable;");
        w.println("    unsigned char is_opaque, tool_not_required;");
        w.println("    unsigned char mobility;  /* getMaterialMobility(): 0 free, 1 no push, 2 immovable */");
        w.println("};");
        w.println();
        w.println("extern const struct material_def MATERIALS[" + mats.size() + "];");
        w.println();
        d.println("const struct material_def MATERIALS[" + mats.size() + "] = {");
        for (Material m : mats)
        {
            d.println(String.format("    {\"%s\", %d, %d, %d, %d, %d, %d, %d, %d},",
                materialName(m), m.isLiquid() ? 1 : 0, m.isSolid() ? 1 : 0, m.blocksMovement() ? 1 : 0,
                m.getCanBurn() ? 1 : 0, m.isReplaceable() ? 1 : 0, m.isOpaque() ? 1 : 0,
                m.isToolNotRequired() ? 1 : 0, m.getMaterialMobility()));
        }
        d.println("};");
        d.println();
        w.println("struct block_def {");
        w.println("    const char *name;");
        w.println("    unsigned char exists;    /* a block object is registered at this id */");
        w.println("    unsigned char opacity;   /* getLightOpacity(), 0..255 */");
        w.println("    unsigned char light;     /* getLightValue(), 0..15 */");
        w.println();
        w.println("    const char *class_name;  /* getClass().getSimpleName(), to switch behavior on */");
        w.println("    float hardness;          /* blockHardness, -1 is unbreakable */");
        w.println("    float resistance;        /* blockResistance as stored (setResistance multiplies by 3) */");
        w.println("    float slipperiness;      /* blockParticleGravity is separate; 0.6 unless ice */");
        w.println("    float particle_gravity;  /* blockParticleGravity, the dig particles' fall pull */");
        w.println();
        w.println("    unsigned char material;      /* index into MATERIALS */");
        w.println("    unsigned char opaque_cube;   /* isOpaqueCube() */");
        w.println("    unsigned char normal_block;  /* renderAsNormalBlock() */");
        w.println("    unsigned char normal_cube;   /* isNormalCube() */");
        w.println("    unsigned char tick_randomly; /* getTickRandomly() */");
        w.println("    unsigned char provides_power;/* canProvidePower() */");
        w.println("    unsigned char tile_entity;   /* instanceof ITileEntityProvider */");
        w.println("    unsigned char collidable;    /* isCollidable() */");
        w.println("    unsigned char render_type;   /* getRenderType() */");
        w.println();
        w.println("    double min_x, min_y, min_z, max_x, max_y, max_z;  /* setBlockBounds at construction */");
        w.println("};");
        w.println();
        w.println("extern const struct block_def BLOCKS[" + IDS + "];");
        w.println();
        d.println("const struct block_def BLOCKS[" + IDS + "] = {");
        for (int id = 0; id < IDS; ++id)
        {
            if (!Block.blockRegistry.containsID(id)) continue;
            Block b = Block.getBlockById(id);
            String name = Block.blockRegistry.getNameForObject(b);
            int opacity = b.getLightOpacity(), light = b.getLightValue();
            if (opacity < 0 || opacity > 255 || light < 0 || light > 15)
                throw new IllegalStateException("block " + id + " " + name + " opacity " + opacity + " light " + light);
            int material = mats.indexOf(b.getMaterial());
            if (material < 0) throw new IllegalStateException("block " + id + " " + name + " material not in MATERIALS");
            d.println(String.format(
                "    [%d] = {\"%s\", 1, %d, %d, \"%s\", %sf, %sf, %sf, %sf, %d, %d, %d, %d, %d, %d, %d, %d, %d, %sf, %sf, %sf, %sf, %sf, %sf},",
                id, name, opacity, light, b.getClass().getSimpleName(),
                Float.toHexString(floatField(Block.class, b, "blockHardness")),
                Float.toHexString(floatField(Block.class, b, "blockResistance")),
                Float.toHexString(b.slipperiness),
                Float.toHexString(b.blockParticleGravity),
                material, b.isOpaqueCube() ? 1 : 0, b.renderAsNormalBlock() ? 1 : 0, b.isNormalCube() ? 1 : 0,
                b.getTickRandomly() ? 1 : 0, b.canProvidePower() ? 1 : 0, b instanceof ITileEntityProvider ? 1 : 0,
                b.isCollidable() ? 1 : 0, b.getRenderType(),
                Double.toHexString(b.getBlockBoundsMinX()), Double.toHexString(b.getBlockBoundsMinY()),
                Double.toHexString(b.getBlockBoundsMinZ()), Double.toHexString(b.getBlockBoundsMaxX()),
                Double.toHexString(b.getBlockBoundsMaxY()), Double.toHexString(b.getBlockBoundsMaxZ())));
        }
        d.println("};");
        d.println();
        // BlockFire.field_149849_a: BlockFire.func_149844_e (can the fire's
        // neighbor catch fire, renderBlockFire's side and top quads read it)
        java.lang.reflect.Field flamF = null;

        for (Class<?> c = net.minecraft.init.Blocks.fire.getClass(); c != null && flamF == null; c = c.getSuperclass())
        {
            try
            {
                flamF = c.getDeclaredField("field_149849_a");
                flamF.setAccessible(true);
            }
            catch (NoSuchFieldException e)
            {
                continue;
            }
        }

        if (flamF == null) throw new IllegalStateException("BlockFire.field_149849_a not found");
        int[] flam = (int[])flamF.get(net.minecraft.init.Blocks.fire);
        w.println("/* BlockFire.func_149844_e: per block id, can the fire renderer draw a");
        w.println(" * side or top quad against this block (> 0 when it can catch fire) */");
        w.println("extern const unsigned char FIRE_FLAM[" + IDS + "];");
        w.println();
        d.println("const unsigned char FIRE_FLAM[" + IDS + "] = {");
        for (int id = 0; id < IDS; ++id)
        {
            if (!Block.blockRegistry.containsID(id)) continue;
            d.println("    [" + id + "] = " + flam[id] + ",");
        }
        d.println("};");
        w.println("#endif");
        w.close();
        d.close();
    }
}