package netherite.oracle;

import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import net.minecraft.enchantment.Enchantment;

/**
 * Writes the enchantment registry as a C header for the native port, read
 * through the oracle's own objects so no value is transcribed by hand. Every
 * value is what the game stores after construction: effectId and weight are the
 * constructor arguments, minLevel/maxLevel and the min/max enchantability
 * windows are the overridden methods evaluated per level, and the type is
 * EnumEnchantmentType ordinal (all, armor, armor_feet, armor_legs, armor_torso,
 * armor_head, weapon, digger, fishing_rod, breakable, bow). canApplyTogether
 * is a bitmask per enchantment, read by calling the game's own method on every
 * pair, so the generated table is exactly the relation the game computes.
 * Run the generator with
 *   java -cp ../out/java/classes:../out/java/lib/*:../out/java/client/1.7.10.jar \
 *     netherite.oracle.EnchantTable ../csrc/engine/enchants.h
 */
public final class EnchantTable
{
    private EnchantTable() {}

    static final int IDS = 256;

    public static void main(String[] args) throws Exception
    {
        net.minecraft.init.Bootstrap.func_151354_b();
        write(new File(args[0]));
        System.out.println("wrote " + args[0]);
    }

    static void write(File out) throws Exception
    {
        Enchantment[] list = Enchantment.enchantmentsList;
        int[] ids = new int[IDS];
        int n = 0;
        for (int i = 0; i < IDS; ++i)
        {
            if (list[i] != null) ids[n++] = i;
        }

        out.getParentFile().mkdirs();
        PrintWriter w = new PrintWriter(new OutputStreamWriter(new FileOutputStream(out), "UTF-8"));
        w.println("/* Minecraft 1.7.10 enchantment registry: what buildEnchantmentList in");
        w.println(" * EnchantmentHelper reads. Generated by netherite.oracle.EnchantTable from the");
        w.println(" * oracle (java -cp out/java/classes:... netherite.oracle.EnchantTable");
        w.println(" * csrc/engine/enchants.h); do not edit by hand. */");
        w.println("#ifndef NETHERITE_ENCHANTS_H");
        w.println("#define NETHERITE_ENCHANTS_H");
        w.println();
        w.println("/* EnumEnchantmentType, in declaration order; a type's canEnchantItem is");
        w.println(" * ported in enchant.c, since it switches on ItemSword/ItemTool/ItemBow; the");
        w.println(" * type table here is the ordinal each entry carries. */");
        w.println("enum enchant_type { E_ALL, E_ARMOR, E_ARMOR_FEET, E_ARMOR_LEGS, E_ARMOR_TORSO, E_ARMOR_HEAD, E_WEAPON, E_DIGGER, E_FISHING_ROD, E_BREAKABLE, E_BOW };");
        w.println();
        w.println("struct enchantment_def {");
        w.println("    unsigned short effect_id;");
        w.println("    unsigned char weight, min_level, max_level, type;");
        w.println("    const char *name;");
        w.println("    unsigned char min_enchantability[5];  /* levels 1..maxLevel */");
        w.println("    unsigned char max_enchantability[5];");
        w.println("};");
        w.println();
        w.println("static const struct enchantment_def ENCHANTS[" + n + "] = {");
        for (int i = 0; i < n; ++i)
        {
            Enchantment e = list[ids[i]];
            int maxLevel = e.getMaxLevel();
            StringBuilder min = new StringBuilder();
            StringBuilder max = new StringBuilder();
            for (int lv = 1; lv <= 5; ++lv)
            {
                if (lv > 1) { min.append(", "); max.append(", "); }
                if (lv <= maxLevel)
                {
                    min.append(e.getMinEnchantability(lv));
                    max.append(e.getMaxEnchantability(lv));
                }
                else
                {
                    // levels above maxLevel are never asked for; 0 keeps the table flat
                    min.append(0);
                    max.append(0);
                }
            }
            w.println(String.format("    {%d, %d, %d, %d, %s, \"%s\", {%s}, {%s}},",
                e.effectId, e.getWeight(), e.getMinLevel(), maxLevel, typeName(e.type), e.getName(),
                min.toString(), max.toString()));
        }
        w.println("};");
        w.println();
        w.println("/* canApplyTogether(a, b) as a bitmask: bit j of CAN_APPLY_TOGETHER[i] is");
        w.println(" * ENCHANTS[i].canApplyTogether(ENCHANTS[j]). The relation is NOT symmetric:");
        w.println(" * lootBonus refuses silkTouch while silkTouch refuses only fortune.");
        w.println(" * buildEnchantmentList calls it as existing.canApplyTogether(candidate), so");
        w.println(" * the port must read this table in that direction. */");
        w.println();
        w.println("static const unsigned int CAN_APPLY_TOGETHER[" + n + "] = {");
        for (int i = 0; i < n; ++i)
        {
            Enchantment a = list[ids[i]];
            long bits = 0;
            for (int j = 0; j < n; ++j)
            {
                if (a.canApplyTogether(list[ids[j]])) bits |= 1L << j;
            }
            w.println(String.format("    0x%08xu,", bits));
        }
        w.println("};");
        w.println();
        w.println("#endif");
        w.close();
    }

    private static String typeName(net.minecraft.enchantment.EnumEnchantmentType t)
    {
        switch (t)
        {
            case all: return "E_ALL";
            case armor: return "E_ARMOR";
            case armor_feet: return "E_ARMOR_FEET";
            case armor_legs: return "E_ARMOR_LEGS";
            case armor_torso: return "E_ARMOR_TORSO";
            case armor_head: return "E_ARMOR_HEAD";
            case weapon: return "E_WEAPON";
            case digger: return "E_DIGGER";
            case fishing_rod: return "E_FISHING_ROD";
            case breakable: return "E_BREAKABLE";
            case bow: return "E_BOW";
            default: throw new IllegalStateException("unknown type " + t);
        }
    }
}