package netherite.oracle;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonPrimitive;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.lang.reflect.Field;
import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.item.ItemArmor;
import net.minecraft.item.ItemBlock;
import net.minecraft.item.ItemFood;
import net.minecraft.item.ItemStack;
import net.minecraft.item.ItemSword;
import net.minecraft.item.ItemTool;

/**
 * Writes the item registry's static properties for the native port, read
 * through the oracle's own methods so no value is transcribed by hand: a C
 * header of the structs and extern declarations, and the one C file that
 * defines the tables. Floats are exact (hex literals). Run with
 * `make -C oracle items-h`.
 */
public final class ItemTable
{
    private ItemTable() {}

    /** The GUI icon and render path for each item id and common metadata. */
    public static void dumpGui(File dir) throws Exception
    {
        JsonArray ids = new JsonArray();
        JsonArray names = new JsonArray();
        for (int id = 0; id < IDS; ++id)
        {
            Item item = Item.getItemById(id);
            if (item == null) { ids.add((JsonElement)null); names.add((JsonElement)null); continue; }
            JsonArray damage = new JsonArray();
            JsonArray display = new JsonArray();
            int maxMeta = id == 373 ? 32768 : id == 383 ? 128 : 16;
            for (int meta = 0; meta < maxMeta; ++meta)
            {
                try
                {
                    ItemStack stack = new ItemStack(item, 1, meta);
                    damage.add(RenderStateProbe.item(stack));
                    display.add(new JsonPrimitive(stack.getDisplayName()));
                }
                catch (RuntimeException badMetadata)
                {
                    damage.add((JsonElement)null);
                    display.add((JsonElement)null);
                }
            }
            ids.add(damage);
            names.add(display);
        }
        PrintWriter w = new PrintWriter(new OutputStreamWriter(
            new FileOutputStream(new File(dir, "item_table.json")), "UTF-8"));
        w.println(ids.toString());
        w.close();
        w = new PrintWriter(new OutputStreamWriter(
            new FileOutputStream(new File(dir, "item_names.json")), "UTF-8"));
        w.println(names.toString());
        w.close();
    }

    /** the ids that share the block array's numeric space */
    static final int IDS = 4096;

    static float floatField(Class<?> c, Object o, String n) throws Exception
    {
        Field f = c.getDeclaredField(n);
        f.setAccessible(true);
        return f.getFloat(o);
    }

    static int intField(Class<?> c, Object o, String n) throws Exception
    {
        Field f = c.getDeclaredField(n);
        f.setAccessible(true);
        return f.getInt(o);
    }

    static boolean boolField(Class<?> c, Object o, String n) throws Exception
    {
        Field f = c.getDeclaredField(n);
        f.setAccessible(true);
        return f.getBoolean(o);
    }

    static Block blockField(Object item) throws Exception
    {
        Field f = ItemBlock.class.getDeclaredField("field_150939_a");
        f.setAccessible(true);
        return (Block)f.get(item);
    }

    /** Index of a tool material in Item.ToolMaterial.values(), for the TOOL_MATERIALS table. */
    static int materialIndex(Item.ToolMaterial m)
    {
        Item.ToolMaterial[] all = Item.ToolMaterial.values();
        for (int i = 0; i < all.length; ++i)
            if (all[i] == m) return i;
        return -1;
    }

    public static void main(String[] args) throws Exception
    {
        net.minecraft.init.Bootstrap.func_151354_b(); // registers blocks and items
        write(new File(args[0]), new File(args[1]));
        System.out.println("wrote " + args[0] + " " + args[1]);
    }

    static void write(File out, File defs) throws Exception
    {
        Item.ToolMaterial[] tools = Item.ToolMaterial.values();

        out.getParentFile().mkdirs();
        PrintWriter w = new PrintWriter(new OutputStreamWriter(new FileOutputStream(out), "UTF-8"));
        PrintWriter d = new PrintWriter(new OutputStreamWriter(new FileOutputStream(defs), "UTF-8"));
        d.println("/* The item registry's tables, declared in " + out.getName() + ", defined here once.");
        d.println(" * Generated by netherite.oracle.ItemTable from the oracle");
        d.println(" * (make -C oracle items-h); do not edit by hand. */");
        d.println("#include \"" + out.getName() + "\"");
        d.println();
        w.println("/* Minecraft 1.7.10 item registry: the static item properties block interaction");
        w.println(" * and player physics read. Generated by netherite.oracle.ItemTable from the");
        w.println(" * oracle (make -C oracle items-h); do not edit by hand. */");
        w.println("#ifndef NETHERITE_ITEMS_H");
        w.println("#define NETHERITE_ITEMS_H");
        w.println();
        w.println("/* what an item is: only one of these carries each kind's fields */");
        w.println("enum item_kind { ITEM_PLAIN, ITEM_BLOCK, ITEM_TOOL, ITEM_SWORD, ITEM_FOOD, ITEM_ARMOR };");
        w.println();
        w.println("/* Item.ToolMaterial, in declaration order */");
        w.println("struct tool_material_def {");
        w.println("    const char *name;");
        w.println("    unsigned char harvest_level, enchantability;");
        w.println("    unsigned short max_uses;");
        w.println("    float efficiency, damage;  /* efficiencyOnProperMaterial, damageVsEntity */");
        w.println("};");
        w.println();
        w.println("extern const struct tool_material_def TOOL_MATERIALS[" + tools.length + "];");
        w.println();
        d.println("const struct tool_material_def TOOL_MATERIALS[" + tools.length + "] = {");
        for (Item.ToolMaterial t : tools)
        {
            d.println(String.format("    {\"%s\", %d, %d, %d, %sf, %sf},",
                t.name(), t.getHarvestLevel(), t.getEnchantability(), t.getMaxUses(),
                Float.toHexString(t.getEfficiencyOnProperMaterial()), Float.toHexString(t.getDamageVsEntity())));
        }
        d.println("};");
        d.println();
        w.println("struct item_def {");
        w.println("    const char *name;        /* registry name: a block's name for an ItemBlock */");
        w.println("    const char *class_name;  /* getClass().getSimpleName(), to switch behavior on */");
        w.println("    unsigned char exists;    /* an item object is registered at this id */");
        w.println("    unsigned char kind;      /* enum item_kind */");
        w.println("    unsigned char max_stack_size;");
        w.println("    unsigned short max_damage;   /* getMaxDamage() */");
        w.println("    unsigned char has_subtypes;");
        w.println("    short block_id;               /* ItemBlock: the block it places, else -1 */");
        w.println("    unsigned char tool_material;  /* ItemTool/ItemSword: TOOL_MATERIALS index, else 0 */");
        w.println("    float efficiency;             /* ItemTool: efficiencyOnProperMaterial, else 0 */");
        w.println("    float damage;                 /* ItemTool: damageVsEntity; ItemSword: attack damage, else 0 */");
        w.println("    unsigned char heal_amount;    /* ItemFood: healAmount, else 0 */");
        w.println("    float saturation;             /* ItemFood: saturationModifier, else 0 */");
        w.println("    unsigned char wolfs_meat;     /* ItemFood: isWolfsFavoriteMeat */");
        w.println("    unsigned char always_edible;  /* ItemFood: alwaysEdible */");
        w.println("    unsigned char armor_type;     /* ItemArmor: 0 helmet, 1 chest, 2 legs, 3 boots */");
        w.println("    unsigned char damage_reduce;  /* ItemArmor: damageReduceAmount */");
        w.println("};");
        w.println();
        w.println("extern const struct item_def ITEMS[" + IDS + "];");
        w.println();
        d.println("const struct item_def ITEMS[" + IDS + "] = {");
        for (int id = 0; id < IDS; ++id)
        {
            if (!Item.itemRegistry.containsID(id)) continue;
            Item it = Item.getItemById(id);
            String name = Item.itemRegistry.getNameForObject(it);
            String cls = it.getClass().getSimpleName();
            String kind = "ITEM_PLAIN";
            int block = -1, toolMaterial = 0, heal = 0, armorType = 0, armorReduce = 0, wolfs = 0, edible = 0;
            float efficiency = 0.0F, damage = 0.0F, saturation = 0.0F;

            if (it instanceof ItemBlock)
            {
                kind = "ITEM_BLOCK";
                block = Block.getIdFromBlock(blockField(it));
            }
            else if (it instanceof ItemTool)
            {
                kind = "ITEM_TOOL";
                toolMaterial = materialIndex(((ItemTool)it).func_150913_i());
                efficiency = floatField(ItemTool.class, it, "efficiencyOnProperMaterial");
                damage = floatField(ItemTool.class, it, "damageVsEntity");
            }
            else if (it instanceof ItemSword)
            {
                kind = "ITEM_SWORD";
                toolMaterial = materialIndex((Item.ToolMaterial)field(ItemSword.class, it, "field_150933_b"));
                damage = floatField(ItemSword.class, it, "field_150934_a");
            }
            else if (it instanceof ItemFood)
            {
                kind = "ITEM_FOOD";
                heal = intField(ItemFood.class, it, "healAmount");
                saturation = floatField(ItemFood.class, it, "saturationModifier");
                wolfs = boolField(ItemFood.class, it, "isWolfsFavoriteMeat") ? 1 : 0;
                edible = boolField(ItemFood.class, it, "alwaysEdible") ? 1 : 0;
            }
            else if (it instanceof ItemArmor)
            {
                kind = "ITEM_ARMOR";
                armorType = ((ItemArmor)it).armorType;
                armorReduce = ((ItemArmor)it).damageReduceAmount;
            }

            if (toolMaterial < 0) throw new IllegalStateException("item " + id + " " + name + " has an unknown ToolMaterial");
            d.println(String.format(
                "    [%d] = {\"%s\", \"%s\", 1, %s, %d, %d, %d, %d, %d, %sf, %sf, %d, %sf, %d, %d, %d, %d},",
                id, name, cls, kind, it.getItemStackLimit(), it.getMaxDamage(), it.getHasSubtypes() ? 1 : 0,
                block, toolMaterial, Float.toHexString(efficiency), Float.toHexString(damage),
                heal, Float.toHexString(saturation), wolfs, edible, armorType, armorReduce));
        }
        d.println("};");
        w.println("#endif");
        w.close();
        d.close();
    }

    static Object field(Class<?> c, Object o, String n) throws Exception
    {
        Field f = c.getDeclaredField(n);
        f.setAccessible(true);
        return f.get(o);
    }
}
