package netherite.oracle;

import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import net.minecraft.block.Block;

/**
 * Writes Block.damageDropped per block id and metadata as a C header: the
 * default Block.getDamageValue(World, x, y, z) that Minecraft.func_147112_ai
 * (pick block) reads for every block without its own override. Run with
 * `make -C oracle pick-h`.
 */
public final class PickTable
{
    private PickTable() {}

    public static void main(String[] args) throws Exception
    {
        net.minecraft.init.Bootstrap.func_151354_b(); // registers blocks and items
        File out = new File(args[0]);
        out.getParentFile().mkdirs();
        PrintWriter w = new PrintWriter(new OutputStreamWriter(new FileOutputStream(out), "UTF-8"));
        w.println("/* Minecraft 1.7.10 Block.damageDropped per block id (0..255) and metadata,");
        w.println(" * the default getDamageValue pick block reads. Generated by");
        w.println(" * netherite.oracle.PickTable from the oracle (make -C oracle pick-h); do not");
        w.println(" * edit by hand. */");
        w.println("#ifndef NETHERITE_PICK_TABLE_H");
        w.println("#define NETHERITE_PICK_TABLE_H");
        w.println();
        w.println("static const unsigned char PICK_DAMAGE_DROPPED[256][16] = {");
        for (int id = 0; id < 256; ++id)
        {
            Block b = Block.getBlockById(id);
            StringBuilder line = new StringBuilder("    {");
            for (int meta = 0; meta < 16; ++meta)
            {
                int d = b == null ? 0 : b.damageDropped(meta);
                if (d < 0 || d > 255) throw new IllegalStateException("damageDropped out of range: " + id + ":" + meta + " " + d);
                line.append(d).append(meta < 15 ? ", " : "");
            }
            line.append("},");
            if (id < 256 && Block.getBlockById(id) != null) line.append(" /* ").append(id).append(" ").append(Block.blockRegistry.getNameForObject(b)).append(" */");
            w.println(line);
        }
        w.println("};");
        w.println();
        w.println("#endif");
        w.close();
        System.out.println("wrote " + args[0]);
    }
}
