package netherite.oracle;

import com.google.gson.JsonObject;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.lang.reflect.Field;
import java.util.List;
import java.util.Map;
import net.minecraft.block.BlockColored;
import net.minecraft.entity.passive.EntitySheep;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemArmor;
import net.minecraft.item.ItemDye;
import net.minecraft.item.ItemStack;
import net.minecraft.item.crafting.CraftingManager;
import net.minecraft.item.crafting.FurnaceRecipes;
import net.minecraft.item.crafting.IRecipe;
import net.minecraft.item.crafting.ShapedRecipes;
import net.minecraft.item.crafting.ShapelessRecipes;
import net.minecraft.server.integrated.IntegratedServer;

/**
 * Writes the recipe registry as a C header for the native port: every entry of
 * CraftingManager.getRecipeList() in list order, then every entry of
 * FurnaceRecipes.getSmeltingList(). Values are read off the live objects
 * through the oracle's own methods and fields, so nothing is transcribed by
 * hand; the special IRecipe classes are listed by getClass().getSimpleName(),
 * in the list order that decides which one findMatchingRecipe reaches first.
 *
 * The shaped list carries the pattern as stored (recipeItems, ready to be read
 * with or without the mirror swap), the output stack, and the size; a shapeless
 * list carries its ingredient list; the special classes carry nothing but their
 * name and the field values the native port needs to reconstruct them from the
 * class alone.
 *
 * The furnace maps are HashMap, whose iteration order is not the order
 * addSmelting ran in. Every distinct input, result, count, damage and float is
 * printed, so the native port can rebuild the same table and let its own
 * iteration order agree with the oracle's. A float prints as raw hex like
 * Float.toHexString, never as decimal.
 *
 * Run through the generic run command (no make target needed):
 *   make -C oracle run SEED=1 CLASS=RecipeTable NAME=recipes \
 *     CMD='{"out":"/abs/path/csrc/engine/recipes.h"}'
 */
final class RecipeTable
{
    private RecipeTable() {}

    static JsonObject run(final IntegratedServer server, final JsonObject cmd) throws Exception
    {
        File out = new File(cmd.get("out").getAsString());
        out.getParentFile().mkdirs();
        int[] counts = write(out);
        JsonObject r = new JsonObject();
        r.addProperty("out", out.getPath());
        r.addProperty("recipes", counts[0]);
        r.addProperty("shaped", counts[1]);
        r.addProperty("shapeless", counts[2]);
        r.addProperty("special", counts[3]);
        r.addProperty("smelting", counts[4]);
        r.addProperty("experience", counts[5]);
        return r;
    }

    /** recipes, shaped, shapeless, special, smelting, experience */
    static int[] write(File out) throws Exception
    {
        List recipes = CraftingManager.getInstance().getRecipeList();
        Map smelting = FurnaceRecipes.smelting().getSmeltingList();
        Map experience = (Map)field(FurnaceRecipes.class, "experienceList").get(FurnaceRecipes.smelting());
        Field tagField = field(ShapedRecipes.class, "field_92101_f");

        int shaped = 0, shapeless = 0, special = 0;
        for (Object o : recipes)
        {
            if (isMapExtending(o)) ++special;
            else if (o instanceof ShapedRecipes) ++shaped;
            else if (o instanceof ShapelessRecipes) ++shapeless;
            else ++special;
        }

        // The native table carries an output's item, count and damage, not its
        // tag. Vanilla has no tagged recipe output or smelting stack, so refuse
        // to generate a table that would silently drop one.
        for (Object o : recipes)
        {
            ItemStack o2 = ((IRecipe)o).getRecipeOutput();
            if (o2 != null && o2.hasTagCompound())
                throw new IllegalStateException("recipe output carries NBT: " + o2.getTagCompound());
        }
        for (Object k : smelting.entrySet())
        {
            Map.Entry e = (Map.Entry)k;
            if (((ItemStack)e.getKey()).hasTagCompound() || ((ItemStack)e.getValue()).hasTagCompound())
                throw new IllegalStateException("smelting stack carries NBT");
        }

        PrintWriter w = new PrintWriter(new OutputStreamWriter(new FileOutputStream(out), "UTF-8"));
        w.println("/* Minecraft 1.7.10 recipes: CraftingManager.getRecipeList() in list order and");
        w.println(" * FurnaceRecipes' two maps. Generated by netherite.oracle.RecipeTable from the");
        w.println(" * oracle (make -C oracle run CLASS=RecipeTable CMD=...); do not edit by hand.");
        w.println(" *");
        w.println(" * A recipe is a struct recipe_def at RECIPES[index]; findMatchingRecipe walks");
        w.println(" * them in that order, exactly like the Java list. Ingredient stacks are");
        w.println(" * IDS[index] in list order, shaped pattern first row first. Every float is a");
        w.println(" * hex literal (raw bits). */");
        w.println("#ifndef NETHERITE_RECIPES_H");
        w.println("#define NETHERITE_RECIPES_H");
        w.println();
        w.println("#include \"items.h\"");
        w.println();
        w.println("enum recipe_kind {");
        w.println("    RECIPE_SHAPED, RECIPE_SHAPELESS,");
        w.println("    RECIPE_ARMOR_DYES, RECIPE_BOOK_CLONING, RECIPE_MAP_CLONING,");
        w.println("    RECIPE_MAP_EXTENDING, RECIPE_FIREWORKS");
        w.println("};");
        w.println();
        w.println("/* One ingredient or one output slot; a null ItemStack has exists 0. */");
        w.println("struct stack_def {");
        w.println("    unsigned char exists;");
        w.println("    short item;         /* item registry id */");
        w.println("    unsigned char count;");
        w.println("    short damage;       /* 32767 is the wildcard an Item or Block argument produced */");
        w.println("};");
        w.println();
        w.println("struct recipe_def {");
        w.println("    unsigned char kind;      /* enum recipe_kind */");
        w.println("    unsigned char mirrored;  /* ShapedRecipes.func_92100_c: the result copies the grid's NBT */");
        w.println("    unsigned char width, height;");
        w.println("    unsigned char size;      /* getRecipeSize() */");
        w.println("    unsigned short items;    /* first index into RECIPE_ITEMS */");
        w.println("    unsigned short count;    /* how many it owns */");
        w.println("    struct stack_def output;");
        w.println("};");
        w.println();
        w.println("static const struct stack_def RECIPE_ITEMS[] = {");
        int[] items = {0};
        int[] itemStart = new int[recipes.size()];
        int[] itemCount = new int[recipes.size()];
        for (int i = 0; i < recipes.size(); ++i)
        {
            Object o = recipes.get(i);
            itemStart[i] = items[0];
            if (o instanceof ShapedRecipes)
            {
                ShapedRecipes r = (ShapedRecipes)o;
                ItemStack[] pat = (ItemStack[])field(ShapedRecipes.class, "recipeItems").get(r);
                for (ItemStack s : pat) printStack(w, items, s);
            }
            else if (o instanceof ShapelessRecipes)
            {
                for (Object s : (List)field(ShapelessRecipes.class, "recipeItems").get(o)) printStack(w, items, (ItemStack)s);
            }
            itemCount[i] = items[0] - itemStart[i];
        }
        w.println("};");
        w.println();
        w.println("static const struct recipe_def RECIPES[" + recipes.size() + "] = {");
        int index = 0;
        for (int i = 0; i < recipes.size(); ++i)
        {
            Object o = recipes.get(i);
            if (o instanceof ShapedRecipes)
            {
                ShapedRecipes r = (ShapedRecipes)o;
                int width = intField(ShapedRecipes.class, r, "recipeWidth");
                int height = intField(ShapedRecipes.class, r, "recipeHeight");
                if (itemCount[i] != width * height)
                    throw new IllegalStateException("shaped recipe " + i + " has " + itemCount[i] + " ingredients, not " + width * height);
                w.println(String.format("    /* %d */ {%s, %d, %d, %d, %d, %d, %d, %s},",
                    index++, isMapExtending(o) ? "RECIPE_MAP_EXTENDING" : "RECIPE_SHAPED",
                    tagField.getBoolean(r) ? 1 : 0, width, height,
                    r.getRecipeSize(), itemStart[i], itemCount[i], out(r.getRecipeOutput())));
            }
            else if (o instanceof ShapelessRecipes)
            {
                ShapelessRecipes r = (ShapelessRecipes)o;
                if (itemCount[i] != r.getRecipeSize())
                    throw new IllegalStateException("shapeless recipe " + i + " has " + itemCount[i] + " ingredients, not " + r.getRecipeSize());
                w.println(String.format("    /* %d */ {%s, 0, 0, 0, %d, %d, %d, %s},",
                    index++, "RECIPE_SHAPELESS", r.getRecipeSize(), itemStart[i], itemCount[i], out(r.getRecipeOutput())));
            }
            else
            {
                w.println(String.format("    /* %d */ {%s, 0, 0, 0, %d, %d, %d, %s},",
                    index++, kind(o), o instanceof IRecipe ? ((IRecipe)o).getRecipeSize() : 0,
                    itemStart[i], itemCount[i], out(((IRecipe)o).getRecipeOutput())));
            }
        }
        w.println("};");
        w.println();
        w.println("/* FurnaceRecipes: one entry per key of smeltingList, in the order the Java");
        w.println(" * HashMap iterates them, with its value. The native port walks these in");
        w.println(" * this order. getSmeltingResult takes the first key whose item matches and");
        w.println(" * whose damage is 32767 or the queried damage. getSmeltingExperience walks");
        w.println(" * experienceList instead and compares the queried stack against each key,");
        w.println(" * which is a *result* stack: SMELT_EXPERIENCE holds those entries, in that");
        w.println(" * map's own order, so the native walk agrees with Java's. */");
        w.println("struct smelting_def {");
        w.println("    struct stack_def input;   /* the map key */");
        w.println("    struct stack_def output;  /* the map value */");
        w.println("    float experience;         /* the value experienceList holds for that output */");
        w.println("};");
        w.println();
        w.println("static const struct smelting_def SMELTING[" + smelting.size() + "] = {");
        int n = 0;
        for (Object k : smelting.entrySet())
        {
            Map.Entry e = (Map.Entry)k;
            ItemStack key = (ItemStack)e.getKey();
            ItemStack value = (ItemStack)e.getValue();
            Float xp = (Float)experience.get(value);
            w.println(String.format("    [%d] = {%s, %s, %sf},",
                n++, stack(key), stack(value), Float.toHexString(xp == null ? 0.0F : xp.floatValue())));
        }
        w.println("};");
        w.println();
        w.println("/* One entry per key of experienceList, in that map's iteration order. */");
        w.println("static const struct smelting_def SMELT_EXPERIENCE[" + experience.size() + "] = {");
        int m = 0;
        for (Object k : experience.entrySet())
        {
            Map.Entry e = (Map.Entry)k;
            w.println(String.format("    [%d] = {%s, {0, 0, 0, 0}, %sf},",
                m++, stack((ItemStack)e.getKey()), Float.toHexString(((Float)e.getValue()).floatValue())));
        }
        w.println("};");
        w.println();
        w.println("#define RECIPE_COUNT " + recipes.size());
        w.println("#define RECIPE_ITEM_COUNT " + items[0]);
        w.println("#define SMELTING_COUNT " + smelting.size());
        w.println();
        w.println("/* The constants the special recipes read, off the live objects: each");
        w.println(" * ItemArmor's material ordinal (0 is CLOTH, the one dyeable material),");
        w.println(" * EntitySheep.fleeceColorTable, ItemDye's firework colour ints, and");
        w.println(" * BlockColored.func_150032_b, the dye damage to fleece index map, which");
        w.println(" * is (~damage) & 15 for every damage including the wildcard 32767. */");
        w.println("struct armor_def {");
        w.println("    short item;");
        w.println("    unsigned char material;   /* ItemArmor.ArmorMaterial ordinal */");
        w.println("};");
        w.println();
        w.println("static const struct armor_def CRAFT_ARMOR[] = {");
        for (int id = 0; id < 4096; ++id)
        {
            if (!Item.itemRegistry.containsID(id)) continue;
            Item it = Item.getItemById(id);
            if (!(it instanceof ItemArmor)) continue;
            w.println(String.format("    {%d, %d},   /* %s */", id,
                ((ItemArmor)it).getArmorMaterial().ordinal(), Item.itemRegistry.getNameForObject(it)));
        }
        w.println("};");
        w.println();
        w.println("static const float CRAFT_FLEECE_COLORS[16][3] = {");
        for (int i = 0; i < 16; ++i)
        {
            w.println("    {" + Float.toHexString(EntitySheep.fleeceColorTable[i][0]) + "f, "
                + Float.toHexString(EntitySheep.fleeceColorTable[i][1]) + "f, "
                + Float.toHexString(EntitySheep.fleeceColorTable[i][2]) + "f},");
        }
        w.println("};");
        w.println();
        w.println("static const int CRAFT_DYE_COLORS[16] = {");
        StringBuilder c = new StringBuilder("    ");
        for (int i = 0; i < 16; ++i)
        {
            if (i != 0) c.append(", ");
            c.append(ItemDye.field_150922_c[i]);
        }
        w.println(c.append(",").toString());
        w.println("};");
        w.println();
        w.println("static const unsigned char CRAFT_DYE_TO_FLEECE[16] = {");
        StringBuilder f = new StringBuilder("    ");
        for (int i = 0; i < 16; ++i)
        {
            if (i != 0) f.append(", ");
            f.append(BlockColored.func_150032_b(i));
        }
        w.println(f.append(",").toString());
        w.println("};");
        w.println();
        w.println("/* The items the special recipes name, by registry id. */");
        w.println("#define CRAFT_ITEM_DYE " + Item.getIdFromItem(Items.dye));
        w.println("#define CRAFT_ITEM_GUNPOWDER " + Item.getIdFromItem(Items.gunpowder));
        w.println("#define CRAFT_ITEM_PAPER " + Item.getIdFromItem(Items.paper));
        w.println("#define CRAFT_ITEM_GLOWSTONE_DUST " + Item.getIdFromItem(Items.glowstone_dust));
        w.println("#define CRAFT_ITEM_DIAMOND " + Item.getIdFromItem(Items.diamond));
        w.println("#define CRAFT_ITEM_FIRE_CHARGE " + Item.getIdFromItem(Items.fire_charge));
        w.println("#define CRAFT_ITEM_FEATHER " + Item.getIdFromItem(Items.feather));
        w.println("#define CRAFT_ITEM_GOLD_NUGGET " + Item.getIdFromItem(Items.gold_nugget));
        w.println("#define CRAFT_ITEM_SKULL " + Item.getIdFromItem(Items.skull));
        w.println("#define CRAFT_ITEM_FIREWORKS " + Item.getIdFromItem(Items.fireworks));
        w.println("#define CRAFT_ITEM_FIREWORK_CHARGE " + Item.getIdFromItem(Items.firework_charge));
        w.println("#define CRAFT_ITEM_WRITTEN_BOOK " + Item.getIdFromItem(Items.written_book));
        w.println("#define CRAFT_ITEM_WRITABLE_BOOK " + Item.getIdFromItem(Items.writable_book));
        w.println("#define CRAFT_ITEM_FILLED_MAP " + Item.getIdFromItem(Items.filled_map));
        w.println("#define CRAFT_ITEM_MAP " + Item.getIdFromItem(Items.map));
        w.println();
        w.println("#endif");
        w.close();
        return new int[] {recipes.size(), shaped, shapeless, special, smelting.size(), experience.size()};
    }

    /** RecipesMapExtending is a ShapedRecipes subclass with its own matching. */
    private static boolean isMapExtending(Object o)
    {
        return o instanceof ShapedRecipes && "RecipesMapExtending".equals(o.getClass().getSimpleName());
    }

    /** The enum name of a special IRecipe, and a check that it is one we ported. */
    private static String kind(Object o)
    {
        String cls = o.getClass().getSimpleName();
        if ("RecipesArmorDyes".equals(cls)) return "RECIPE_ARMOR_DYES";
        if ("RecipeBookCloning".equals(cls)) return "RECIPE_BOOK_CLONING";
        if ("RecipesMapCloning".equals(cls)) return "RECIPE_MAP_CLONING";
        if ("RecipesMapExtending".equals(cls)) return "RECIPE_MAP_EXTENDING";
        if ("RecipeFireworks".equals(cls)) return "RECIPE_FIREWORKS";
        throw new IllegalStateException("recipe class " + cls + " has no native kind");
    }

    private static void printStack(PrintWriter w, int[] n, ItemStack s)
    {
        w.println(String.format("    [%d] = %s,   /* %s */", n[0]++, stack(s), note(s)));
    }

    private static String note(ItemStack s)
    {
        return s == null ? "empty" : s.getItem() + " x" + s.stackSize + " d" + s.getItemDamage();
    }

    private static String stack(ItemStack s)
    {
        if (s == null) return "{0, 0, 0, 0}";
        return "{1, " + net.minecraft.item.Item.getIdFromItem(s.getItem()) + ", " + s.stackSize
            + ", " + s.getItemDamage() + "}";
    }

    private static String out(ItemStack s)
    {
        return "{" + (s == null ? "0, 0, 0, 0"
            : 1 + ", " + net.minecraft.item.Item.getIdFromItem(s.getItem()) + ", " + s.stackSize + ", " + s.getItemDamage()) + "}";
    }

    static Field field(Class<?> c, String name) throws Exception
    {
        Field f = c.getDeclaredField(name);
        f.setAccessible(true);
        return f;
    }

    static int intField(Class<?> c, Object o, String n) throws Exception
    {
        return field(c, n).getInt(o);
    }
}