package netherite.oracle;

import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import net.minecraft.entity.EntityList;
import net.minecraft.stats.Achievement;
import net.minecraft.stats.AchievementList;
import net.minecraft.stats.StatBase;
import net.minecraft.stats.StatList;
import net.minecraft.world.biome.BiomeGenBase;

/**
 * Writes the StatList registry as a C header for the native port, read from
 * the live stat objects after Bootstrap: per block or item id, which stat the
 * mineBlock, useItem, craftItem and breakItem arrays hold after
 * replaceAllSimilarBlocks (the id in its statId, -1 for null), the general
 * stats and achievements in registration order, the egg entities, and
 * BiomeGenBase.field_150597_n. Run with `make -C oracle stats-h`.
 */
public final class StatTable
{
    private StatTable() {}

    public static void main(String[] args) throws Exception
    {
        net.minecraft.init.Bootstrap.func_151354_b(); // registers blocks, items and StatList
        write(new File(args[0]));
        System.out.println("wrote " + args[0]);
    }

    static int suffix(StatBase s)
    {
        if (s == null) return -1;
        String id = s.statId;
        return Integer.parseInt(id.substring(id.lastIndexOf('.') + 1));
    }

    static void array(PrintWriter w, String name, StatBase[] a)
    {
        w.println("static const short " + name + "[4096] = {");
        StringBuilder line = new StringBuilder("   ");
        for (int i = 0; i < 4096; ++i)
        {
            line.append(' ').append(suffix(a[i])).append(',');
            if (line.length() > 88) { w.println(line); line = new StringBuilder("   "); }
        }
        if (line.length() > 3) w.println(line);
        w.println("};");
        w.println();
        for (int i = 4096; i < a.length; ++i)
            if (a[i] != null) throw new IllegalStateException(name + " has an id past 4095: " + i);
    }

    static void write(File out) throws Exception
    {
        out.getParentFile().mkdirs();
        PrintWriter w = new PrintWriter(new OutputStreamWriter(new FileOutputStream(out), "UTF-8"));
        w.println("/* Minecraft 1.7.10 StatList registry: the stat each per-id array holds after");
        w.println(" * replaceAllSimilarBlocks, the general stats and achievements in registration");
        w.println(" * order, the egg entities and BiomeGenBase.field_150597_n. Generated by");
        w.println(" * netherite.oracle.StatTable from the oracle (make -C oracle stats-h); do not");
        w.println(" * edit by hand. */");
        w.println("#ifndef NETHERITE_STATS_TABLE_H");
        w.println("#define NETHERITE_STATS_TABLE_H");
        w.println();
        w.println("/* per block (mine) or item id: the id in the registered stat's statId");
        w.println(" * (stat.mineBlock.<id>), -1 when the array holds null there */");
        array(w, "STAT_TABLE_MINE", StatList.mineBlockStatArray);
        array(w, "STAT_TABLE_USE", StatList.objectUseStats);
        array(w, "STAT_TABLE_CRAFT", StatList.objectCraftStats);
        array(w, "STAT_TABLE_BREAK", StatList.objectBreakStats);

        List general = StatList.generalStats;
        w.println("/* StatList.generalStats, in registration order */");
        w.println("#define STAT_TABLE_NGENERAL " + general.size());
        w.println("static const char *const STAT_TABLE_GENERAL[" + general.size() + "] = {");
        for (Object o : general) w.println("    \"" + ((StatBase)o).statId + "\",");
        w.println("};");
        w.println();

        List ach = AchievementList.achievementList;
        w.println("/* AchievementList.achievementList, in registration order, with the index");
        w.println(" * of the parent (-1 independent) */");
        w.println("#define STAT_TABLE_NACH " + ach.size());
        w.println("static const char *const STAT_TABLE_ACH[" + ach.size() + "] = {");
        for (Object o : ach) w.println("    \"" + ((Achievement)o).statId + "\",");
        w.println("};");
        w.println("static const signed char STAT_TABLE_ACH_PARENT[" + ach.size() + "] = {");
        for (Object o : ach)
        {
            Achievement a = (Achievement)o;
            w.println("    " + (a.parentAchievement == null ? -1 : ach.indexOf(a.parentAchievement)) + ", /* " + a.statId + " */");
        }
        w.println("};");
        w.println();

        w.println("/* EntityList.entityEggs in the map's iteration order: entity id, name */");
        w.println("#define STAT_TABLE_NEGG " + EntityList.entityEggs.size());
        w.println("static const struct { int id; const char *name; } STAT_TABLE_EGG[" + EntityList.entityEggs.size() + "] = {");
        for (Iterator it = EntityList.entityEggs.entrySet().iterator(); it.hasNext();)
        {
            Map.Entry e = (Map.Entry)it.next();
            int id = ((Integer)e.getKey()).intValue();
            w.println("    {" + id + ", \"" + EntityList.getStringFromID(id) + "\"},");
        }
        w.println("};");
        w.println();

        w.println("/* BiomeGenBase.field_150597_n: the biomes exploreAllBiomes asks for */");
        w.println("#define STAT_TABLE_NEXPLORE " + BiomeGenBase.field_150597_n.size());
        w.println("static const unsigned char STAT_TABLE_EXPLORE[" + BiomeGenBase.field_150597_n.size() + "] = {");
        StringBuilder line = new StringBuilder("   ");
        BiomeGenBase[] all = BiomeGenBase.getBiomeGenArray();
        for (int i = 0; i < all.length; ++i)
            if (all[i] != null && BiomeGenBase.field_150597_n.contains(all[i])) line.append(' ').append(i).append(',');
        w.println(line);
        w.println("};");
        w.println();
        w.println("#endif");
        w.close();
    }
}
