/* blockmodels.h - PUBLIC contract for the magma block model + atlas layer.
 *
 * Maps mc-sim CB_* block ids to per-face atlas sprites, biome tints, and a
 * CrRenderLayer, and exposes the stitched real-MC atlas (with a gamma-correct
 * mip chain) as a CrTexture. The mesher/shader include ONLY this header.
 *
 * Sprite indices are those of assets/atlas_gen.h (generated by build_atlas.py).
 */
#ifndef MAGMA_BLOCKMODELS_H
#define MAGMA_BLOCKMODELS_H

#include "core/types.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Cube faces, matching net.minecraft.util.EnumFacing.getIndex(). */
enum {
    BM_DOWN  = 0,
    BM_UP    = 1,
    BM_NORTH = 2,
    BM_SOUTH = 3,
    BM_WEST  = 4,
    BM_EAST  = 5
};

/* Biome tint classes applied to a face (multiplied into the texel by the shader). */
enum {
    BM_TINT_NONE    = 0,
    BM_TINT_GRASS   = 1,
    BM_TINT_FOLIAGE = 2,
    BM_TINT_WATER   = 3,
    /* BlockColors.java WATERLILY: fixed in-world 0x208030 (not foliage). */
    BM_TINT_LILY    = 4,
    /* BlockColors leaves: spruce/birch fixed ColorizerFoliage pine/birch. */
    BM_TINT_FOLIAGE_PINE  = 5,
    BM_TINT_FOLIAGE_BIRCH = 6
};

/* Block model geometry kinds. CUBE uses the classic per-face full-cube path;
 * every other kind is a NON-CUBE model built by the mesher through the render-opt
 * facebakery kernels (renderkernels/rk_31..34). */
enum {
    BM_KIND_CUBE = 0,     /* full (or arbitrary) axis-aligned single box */
    BM_KIND_CROSS,        /* two diagonal billboards (flowers/tall grass/saplings) */
    BM_KIND_SLAB_BOTTOM,  /* bottom half box (y 0..8) */
    BM_KIND_SLAB_TOP,     /* top half box (y 8..16) */
    BM_KIND_STAIRS,       /* bottom slab + back upper box (faces +Z / south) */
    BM_KIND_FENCE,        /* centre post + N/S/E/W connector bars */
    BM_KIND_WALL,         /* connection-state cobblestone-wall post + arms */
    BM_KIND_FLUID,        /* water/lava: top surface lowered to 14/16 when no fluid above */
    /* Vanilla models/block/waterlily.json: zero-thickness plane at y=0.25/16,
     * up+down faces only. NOT a full cube (that bug made swamp pads look like
     * green boxes). */
    BM_KIND_LILY,
    /* snow_height2.json: box y 0..2 (1/8 block), all faces. */
    BM_KIND_SNOW_LAYER,
    /* vine_*.json: thin cutout plane on one side face (south z=15.2 representative). */
    BM_KIND_VINE,
    /* cactus.json: inset side faces (approx: full cube cutout; sides inset 1px). */
    BM_KIND_CACTUS,
    /* BlockFire supported-from-below multipart: one weighted fire_floor model
     * plus four weighted/rotated fire_side models, 12 baked quads total. */
    BM_KIND_FIRE,
    /* portal_{ns,ew}.json: metadata axis selects a 4/16-thick two-face panel. */
    BM_KIND_PORTAL,
    /* end_portal_frame_{empty,filled}.json: 13/16 base plus optional eye. */
    BM_KIND_END_FRAME,
    /* End-pillar cage pane network, connected to adjacent panes/full cubes. */
    BM_KIND_IRON_BARS,
    /* Standing/wall torch; legacy metadata selects its attachment side. */
    BM_KIND_TORCH
};

typedef struct {
    int sprite; /* index into assets/atlas_gen.h CR_ATLAS_SPRITES / CR_SPRITE_* */
    int tint;   /* BM_TINT_* */
} BmFace;

typedef struct {
    int    is_air;
    int    is_full_cube;
    int    layer;      /* CrRenderLayer */
    int    kind;       /* BM_KIND_* geometry */
    BmFace face[6];    /* indexed by BM_DOWN..BM_EAST */
} BmBlock;

/* Per CB_* id (mc-sim block id). Never NULL: unknown/out-of-range -> stone. */
const BmBlock *bm_block(int cb_id);

/* Atlas rect for a sprite index, normalized into [0,1] over the whole atlas. */
void bm_sprite_uv(int sprite, float *u0, float *v0, float *u1, float *v1);

/* Sprite index of grass_side_overlay (vanilla block/grass.json second element:
 * a biome-tinted overlay quad on each grass side face). */
int bm_grass_side_overlay_sprite(void);

/* The real-MC atlas as a CrTexture, including a gamma-correct box-filter mip
 * chain down to 1x1. Backed by static storage; safe to copy by value. */
CrTexture bm_atlas(void);

/* Advance water/lava/fire TextureAtlasSprites from the client TextureMap tick.
 * Metadata frame times and custom physical-frame sequences are generated from
 * the vanilla 1.11.2 jar.  Mutates level zero and lazily rebuilds all mips. */
void bm_atlas_set_animation_tick(long long client_tick);
/* Restore the physical frame zero uploaded by TextureMap during resource
 * loading. QRL's pinned-animation mixin cancels every updateAnimation call. */
void bm_atlas_set_animation_physical_zero(void);
/* Select the exact TextureAtlasSprite portal frame recorded by the oracle. */
void bm_atlas_set_portal_frame(int frame);

#ifdef __cplusplus
}
#endif
#endif /* MAGMA_BLOCKMODELS_H */
